### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by s-moon** [MicrosoftDocs/Contribute#104]
I've noticed that there are some places that aren't consistent but being unsure which is your preference, have chosen to raise an issue instead.

For example, in some places you refer to pressing a control key combination as ```Control+key``` but others, it's ```CTRL+key```.

Another example is in the use of Git. Sometimes it is written as ```Git``` and others as ```git```.

If you state which you prefer, I can alter the docs.

**Comment by JasonWHowell** [comment]
@MonicaRush I couldn't determine the best answer, because our style guides didn't detail this. Could you also sleuth to see if we have sufficient precedent to help answer @s-moon 's concern. 

Thanks, Jason

**Comment by MonicaRush** [comment]
@s-moon @JasonWHowell 
Should be:
•	Git (not git)
•	Ctrl + Key (ex. Ctrl + Shift)
Thanks for bringing these up. We're going to do a consistency check for things like this and will make your fixes soon. Consistency makes for a higher quality guide. Thanks again.

**Comment by s-moon** [comment]
Thanks

**Comment by JasonWHowell** [comment]
@MonicaRush Anything else we need to do on this thread?

**Comment by MonicaRush** [comment]
@s-moon @JasonWHowell We are done with this issue and I will close. Thanks for the cattle prod. We will make these changes within the next few weeks as we embark on a global search and replace to clean up term inconsistency.
