### ISSUE TITLE
Locale flagging is looking too deep in the URL

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/Contribute#121]
EX: on https://github.com/MicrosoftDocs/windows-driver-docs/pull/978/checks it is flagging part of the latter url, rather than just looking at `docs.microsoft.com/(en-us)/foobar` pattern

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b1f3e76-a163-54ee-a2d4-fe4095285e54
* Version Independent ID: a60814e1-6b5f-5b13-584b-26c73384caec
* Content: [Locale-specific links - Contributor Guide](https://docs.microsoft.com/en-us/contribute/validation-reference/locale-specific-links)
* Content Source: [Contribute/validation-reference/locale-specific-links.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/validation-reference/locale-specific-links.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
@meganbradley could you please triage this feedback on the new validation for language in the URL.

**Comment by meganbradley** [comment]
@nschonni this is fixed - thanks!

CC @JasonWHowell
