### ISSUE TITLE
"Links in selectors" section is confusing

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/Contribute#126]
The following sentence is hard to understand, maybe because the term "selector" is referring to a concept that isn't defined in this doc.
&gt; If you have selectors that are embedded in an include--as does the Azure documentation team--use the following link structure:

There is also a trailing html content tag `-->` that isn't explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcff0d60-cd99-d88d-9e21-bee20c17a4de
* Version Independent ID: ff9c4a5e-f283-9c95-b8fb-a3adb87460cc
* Content: [How to use links in documentation - Contributor Guide](https://docs.microsoft.com/en-us/contribute/how-to-write-links)
* Content Source: [Contribute/how-to-write-links.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-links.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
@nschonni I'll add something to explain the context of selectors. If by the &gt html tag you referred to, could be that `-->` is part of the syntax.

#127 @gewarren do you have any more context to add?

**Comment by nschonni** [comment]
No more context to add, i was just lost trying to understand the example

**Comment by JasonWHowell** [comment]
@nschonni if in doubt, please share the PR you are working on and we can research further. I don't have the answer without testing it, which is time consuming. Thanks again, Jason
