### ISSUE TITLE
Some clarifications please

### ISSUE THREAD

**Issue by SimpleSamples** [MicrosoftDocs/Contribute#130]
This says "click the pencil icon" then "Once you have made your changes, scroll" ... "your PR and click Propose file change" then "ask the owners of the repository to "pull" your changes" then "GitHub automatically creates a fork". It is not clear what a fork is; when is it created? What do we call what we get after clicking the pencil icon? If I want to post a question somewhere asking where the edits are that I have made previously that have not had a pull requested then how do I refer to that?

Also, I don't understand "GitHub creates a new branch in the target repo". When is that done? Is that the same thing as a fork or is it something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
@SimpleSamples sorry for the delay in answering. I just now saw your post. 

1> It is not clear what a fork is; when is it created? 
A fork is created automatically when you edit the file if you read-access, which is the default on most Microsoft docs. Essentially the master copy is read only, so the edit takes place in in a working branch (patch branch) under your own name (your fork). To save the changes back into master, you have to do a pull request to incorporate those changes back into the original. 

2> What do we call what we get after clicking the pencil icon? 
There are two pencils. The first Edit icon (Edit this document) to take you from the docs page to the GitHub site where the markdown file can be edits. The second click on the pencil (Edit this file) in GitHub lets you edit the the markdown file in the browser. Maybe we'd call it the "web editor" page in GitHub.

3> If I want to post a question somewhere asking where the edits are that I have made previously that have not had a pull requested then how do I refer to that?

To have Q&A, You'd need a pull request to start a conversation. Or file an issue if there is no pull request.

You could look at your branches. Each time you click edit, it will make a separate patch branch. The URL depends on the repository though. For example, https://github.com/MicrosoftDocs/azure-docs/branches. If you have a branch with your githandle:patch-1, githandle:patch-2, githandle:patch-3, etc. Those are different attempts to edit documents. The system creates a patch branch edit time you use the web editor on a read-only document. 

Thanks, Jason
