### ISSUE TITLE
social.msdn and social.technet localization redirects don't work

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/Contribute#131]
EX: if you remove the locale from https://social.msdn.microsoft.com/Forums/en-US/home?forum=vsmantest it drops the query string while redirecting back to `en-us`.
Not sure if the checks actually flag those links right now, but just one issue i've noticed if people try and remove it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b1f3e76-a163-54ee-a2d4-fe4095285e54
* Version Independent ID: a60814e1-6b5f-5b13-584b-26c73384caec
* Content: [Locale-specific links - Contributor Guide](https://docs.microsoft.com/en-us/contribute/validation-reference/locale-specific-links)
* Content Source: [Contribute/validation-reference/locale-specific-links.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/validation-reference/locale-specific-links.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @dend 

This scenario does work for docs.microsoft.com (for example, remove the locale info from https://docs.microsoft.com/en-us/dotnet/api/system.string?view=netcore-2.1 to test).

Should this move to MicrosoftDocs/feedback?

**Comment by JasonWHowell** [comment]
@nschonni I've had this conversation with the forums owners before, but it was decided not to fix. For now keep en-us in links to the MSDN forums. It's a lot of work to fix and the workaround is fairly easy for most folks. Thanks, Jason
