### ISSUE TITLE
Issues with the OPS custom Markdown extensions section

### ISSUE THREAD

**Issue by pkulikov** [MicrosoftDocs/Contribute#138]
The [OPS custom Markdown extensions](https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown#ops-custom-markdown-extensions) section has a couple of issues:
- There are no referenced articles:
  >For the complete list, refer to "Markdig and Markdown extensions" and "Code snippets" in the table of contents.
- The section itself seems to be outdated and a duplicate, as the [Markdown reference for OPS](https://docs.microsoft.com/en-us/contribute/markdown-reference) looks to be a new article about OPS-specific Markdown. The only thing a new article misses is the description of the [includes](https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown#includes)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c11e26-0b4e-c922-1578-a487b16a7b7b
* Version Independent ID: 432d205a-c041-e6f7-0776-b13486fe2a1f
* Content: [How to use Markdown for writing Docs - Contributor Guide](https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown#tables)
* Content Source: [Contribute/how-to-write-use-markdown.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-use-markdown.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by tdykstra** [comment]
After https://github.com/MicrosoftDocs/docs-help-pr/pull/2807 and https://github.com/MicrosoftDocs/docs-help-pr/pull/2783 in the internal repo are merged, I'll create a PR in this repo that will address both of these issues.

**Comment by Jim-Parker** [comment]
@pkulikov this issue was addressed by the PRs listed above, as well as #358. I'm closing this issue. Let me know if you have any other questions. Thanks.
