### ISSUE TITLE
What Markdown engine does OPS implement?

### ISSUE THREAD

**Issue by pkulikov** [MicrosoftDocs/Contribute#140]
The current docs are not consistent.

The [How to use Markdown for writing Docs](https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown) article says:
> Additionally, Open Publishing Services (OPS) implements Markdig Markdown Parser.

I guess, it corresponds to the `"markdownEngineName": "markdig"` setting in the *docfx.json* file.

However, the [Using links in documentation](https://docs.microsoft.com/en-us/contribute/how-to-write-links) article says:
> The docs.microsoft.com site backend uses Open Publishing Services (OPS) which implements DocFX Flavored Markdown (DFM)

Again a guess, it corresponds to the `"markdownEngineName": "dfm-latest"` setting in the *docfx.json* file.

**Comment by JasonWHowell** [comment]
Both DFM and Markdig. It depends on the settings in the repo / docset. I think we are migrating towards markdig, but not sure of the progress on that.

**Comment by JasonWHowell** [comment]
@SyntaxC4 could you confirm which markdown engine name we should lead with?

**Comment by JasonWHowell** [comment]
Updating the two articles to match better in #196 and #197.
