### ISSUE TITLE
Provide flexibility on the time of day for publishing

### ISSUE THREAD

**Issue by BillWagner** [MicrosoftDocs/Contribute#142]
We've put very strict guarantees on [several publishing activities](https://docs.microsoft.com/contribute/how-to-write-workflows-major#publishing). Based on https://github.com/MicrosoftDocs/Contribute/pull/133#discussion_r233097158 we should provide a bit more wiggle room while still guaranteeing responsiveness.

**Comment by JasonWHowell** [comment]
@BillWagner is this important enough to keep, or to backlog forever?
