### ISSUE TITLE
Consolidate the .NET specific guidance and the general guidance

### ISSUE THREAD

**Issue by BillWagner** [MicrosoftDocs/Contribute#143]
PR #133 brought the .NET Specific guidance to the external contributor guide, in a .NET Specific guidance.

Historically, the .NET guidance had grown in the GitHub repo for .NET docs. That's leaved a bit of a muddle.  Some content is repeated, some is organized differently, some is modified.

We should rationalize as follows:

- [ ] Where the .NET guidance duplicates the general guidance, the best content should be in the general guidance.
- [ ] The .NET guidance should point to the general guidance in more locations to highlight the general practices.
- [ ] The .NET specific section should be clear that these are specific to that section and modify (or extend) the general guidance. Links should be provided.
- [ ] The major workflow should be updated.  See https://github.com/MicrosoftDocs/Contribute/pull/133#discussion_r232809487 for pertinent feedback.

**Comment by JasonWHowell** [comment]
@BillWagner is this important enough to keep, or to backlog forever?

**Comment by BillWagner** [comment]
I think we can close this.

We've continued to update the public guidance over the past several montsh.

I'll also close the related internal [work item](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1411509).
