### ISSUE TITLE
Microsoft.Bcl.Build

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/Contribute#145]
It would be handy to have about what the Microsoft.Bcl.Build.nuget package is (see https://www.nuget.org/packages/Microsoft.Bcl.Build). The best I could find is here https://blogs.msdn.microsoft.com/bclteam/p/bclbuild/ but it really doesn't tell much. I discovered this library in an open source project and it would be really handy to have some idea what it does. So I know if it is safe to remove it.

**Comment by JasonWHowell** [comment]
@martingbrown I don't think the folks on the contributor guide will know much about that. Maybe ping @terrajobst for details.

**Comment by terrajobst** [comment]
The quick answer is: it’s legacy.

The longer answer is: it works around many issues in NuGet that all got addressed with ‘PackageReference’.

**Comment by JasonWHowell** [comment]
@martingbrown I have a side question when you have a moment - How did you find this forum for filing issues?  I'm just curious if there is a link to the Contribute repo somewhere, or you stumbled on it another way. Sorry for the distraction. ~Jason

**Comment by martingbrown** [comment]
I forget how exactly i ended up here. I think i started with feedback on a docs.microsoft.com page and then clicked about github for a bit.
