### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by ravisha22** [MicrosoftDocs/Contribute#148]
The documentation is incomplete without explaining what the ClientID or how to retrieve it. Please think from the perspective of the customers who will try and DIY these tools. The tool itself is way more complicated that it should be and on top of it, these instructions assume the person has knowledge on these parameters.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@ravisha22 

This issue doesn't apply to the document it's tagged for.  I'm closing it. You should open an issue on the document where your concern applies.
