### ISSUE TITLE
L-series description

### ISSUE THREAD

**Issue by jbaick** [MicrosoftDocs/Contribute#151]
Pricing - Linux Virtual Machines:
https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/

The NoSQL classification for L series is incorrect for Cloudera.  Cloudera does not currently support L series machine types.  Please remove Cloudera from this sentence: L-series instances are storage optimized virtual machines for low latency workloads such as NoSQL databases (e.g. Cassandra, MongoDB, Cloudera, and Redis).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/#review-open-prs)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
@jbaick I have tracked your feedback with the azure.microsoft.com team. Unfortunately my team does not have direct access to edit those pages.
