### ISSUE TITLE
Suggestions to improve the style guide

### ISSUE THREAD

**Issue by BillWagner** [MicrosoftDocs/Contribute#156]
From @pkulikov on dotnet/docs#4358:  

I think there are several minor improvements for the current [style guide](https://github.com/dotnet/docs/blob/master/styleguide/template.md):
- **Metadata** section can mention when **ms.date** should be or shouldn't be updated.
- **Links** section should describe how to reference [https://docs.microsoft.com/en-us/](https://docs.microsoft.com/en-us/) pages that don't belong to dotnet/docs repo. It's docs.microsoft specific feature, though.
- **Links to APIs** section. Examples of using \* after UID can be given in the same way as examples for System.String at the same section (raw file contains https links, not xref).
- **Code** section. The rendering of the list with parameters of `'[!code...]` construct is broken: only two levels instead of intended three.
- **Includes** section. The example is broken: no *sampleinclude.md* file in the repo. Also, what should be put between the square brackets at the `[!INCLUDE[what goes here?](relative link to the file)]` construct?
- At last, we can add the link to the [MIcrosoft Writing Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/) or [Top 10 tips](https://docs.microsoft.com/en-us/style-guide/top-10-tips-style-voice) from there.

@BillWagner @mairaw @rpetrusha what do you think?

See dotnet/docs#4358 for discussion on this issue.

**Comment by JasonWHowell** [comment]
@BillWagner is this important enough to keep, or to backlog forever?

**Comment by tdykstra** [comment]
* ms.date explanation is already added
* Out-of-repo links are covered by [Links](https://docs.microsoft.com/en-us/contribute/how-to-write-links)
* Links to APIs are covered in [API links section](https://docs.microsoft.com/en-us/contribute/dotnet-style-guide#links-to-apis).  This content needs to be added to the Links doc and removed from here.  I'll create a new issue for that.
* Code section - I'm working on copying the code-in-docs article to the this repo; when that happens I'll remove the code section from the .NET template doc
* Includes are covered by the markdown reference doc.
* Style guide link is added by https://github.com/MicrosoftDocs/Contribute/pull/356

#please-close
