### ISSUE TITLE
Markdig question

### ISSUE THREAD

**Issue by KingdomOfEnds** [MicrosoftDocs/Contribute#166]
Quick question about Markdig support. There are some really cool new features that are supported  in the current version: https://github.com/lunet-io/markdig. I'm particularly excited about Grid Table support since it allows multi-column subdivisions, any element in a row (so numbered lists for example). Are such features presently supported? If not, is there a timeframe on when they might be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd2bb3d-3104-1be7-7232-8a194074af4b
* Version Independent ID: 2efecbe2-8538-8659-7740-6f8852f7875b
* Content: [Markdown reference for docs.microsoft.com - Contributor Guide](https://docs.microsoft.com/en-us/contribute/markdown-reference)
* Content Source: [Contribute/markdown-reference.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/markdown-reference.md)
* Product: **non-product-specific**
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by meganbradley** [comment]
Assigning markdig question to @cillroy .

**Comment by baardhermansen** [comment]
@meganbradley Must be able to close this now, given the statement at the top of this article; "Docs uses the Markdig Markdown engine."?

**Comment by Jim-Parker** [comment]
@meganbradley is this still being worked on?

**Comment by JasonWHowell** [comment]
I pinged Docs support to see if anyone knows. I don't know off the top of my head.

**Comment by cillroy** [comment]
We are currently evaluating when the docs platform will refresh our instance of markdig, and evaluate the impact it might have on our rendering

**Comment by JasonWHowell** [comment]
Thanks @cillroy So for now, the answer is no, but in the future perhaps. @KingdomOfEnds hope that helps answer your question. I'll close out the thread now. #please-close
