### ISSUE TITLE
Is docs.microsoft.com itself open source?

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/Contribute#174]
Hi, is this website itself open-sourced on GitHub as well? I'm talking about the GUI, not its contents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/#get-more-involved)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
It's a hybrid, but much of the work is open source.  See the [docfx])https://github.com/dotnet/docfx) project for the part of the project that's open.

/cc @DuncanmaMSFT for more details.

I'll close this as a question, with an answer.

**Comment by weitzhandler** [comment]
@BillWagner thanks for your quick response, i'm not willing to generate docs, I'm talking about the website interface.
For instance, where do I find the code that renders the highlighted region in the docs website:

![image](https://user-images.githubusercontent.com/2716316/50609787-6794ae00-0ed9-11e9-92a0-d3e7536200d5.png)

**Comment by BillWagner** [comment]
@weitzhandler that's a question for @DuncanmaMSFT

**Comment by maheralkhatib10** [comment]
I do appreciate all your help guys.. I'm still learning here and all of you are much more smarter than me.. I'm going to help you back one day,,but gosh... y'all make it look to easy..thnx

**Comment by lailabeauty** [comment]
that is great intuitive from MS and GitHub, I hope I can contribute too

**Comment by DuncanmaMSFT** [comment]
@weitzhandler our site code is not open source, but our GitHub issues based feedback system is written by the same dev as https://utteranc.es/, which is an open source GitHub issues based feedback system intended to deliver the same functionality for anyone who wants to include it on their site
