### ISSUE TITLE
OleLoadPicturePath 

### ISSUE THREAD

**Issue by DaveInCaz** [MicrosoftDocs/Contribute#178]
Is the page:
https://docs.microsoft.com/en-us/windows/desktop/api/olectl/nf-olectl-oleloadpicturepath

Part of this project? Is there somewhere I can make a comment about its content?

Thanks

**Comment by JasonWHowell** [comment]
Hi @DaveInCaz 
That page appears to be auto-generated reference content that doesn't have the feedback control turned on, and there is not a point of contact that actively monitors feedback.  

No, it's not directly related to the contribute project.

What's the nature of your comment? 

Thanks, Jason

**Comment by DaveInCaz** [comment]
I recently had an issue where I was able to load a 32-bit ICO file on one PC where it worked fine, but they was unable to do so on a second PC.

It was a Win10 x64 PC which allowed the 32-bit icon, and Win7 x32 which did not. I was surprised that this was a system-dependent feature.

The function in use was OleLoadPicturePath(). So it seems like it behaves differently on these two different PCs. I would not have expected the Windows API to change in this way. It seems like a bug, since it appears that it is not fully backwards-compatible.

---

Note that in my case this function was being called from a VB6 program.  And for use from VB6 this change to its behavior is pretty bad - because if that image data is saved into a form control it can be reloaded on another PC later (when you have deployed your app) and it causes a crash. But VB6 itself isn't the problem; just so happens that is how we were using the results of OleLoadPicturePath().

**Comment by JasonWHowell** [comment]
Thanks @DaveInCaz 

That's an interesting scenario. You are clever to figure it the 32-bit vs 64-bit compatibility problem. 

Unfortunately this isn't a good place to track SDK bugs, so we aren't set up to track that here and I don't have the right connections to suggest where to file bugs there.

Looks like you already tried StackOverflow too: 
https://stackoverflow.com/questions/54253845/how-does-icon-image-format-support-vary-by-version-of-windows

I'll close this out here. 

Thanks, Jason

**Comment by DaveInCaz** [comment]
Really what I'd like is for this to get forwarded to the right development team at Microsoft to address it (either explain it or fix it). Is there some other way to file a bug / ticket for the library / group / whatever who owns that API?

**Comment by JasonWHowell** [comment]
@DaveInCaz I hear you. If you need action on feedback, that is best handled through a call to support or locate the folks you want to target. I also don't know the right folks. I wish it was easier, but with the thousands of people and teams in the Microsoft ecosystem, its not so simple to shoot into the dark for me either. The contribute guide that explains how to write docs isn't the right place. If I find a connection, I'll let you know though. I'm sure I'll run across someone, but it might be a while.
