### ISSUE TITLE
Suggestion: Add "Docker" to supported languages in "How to include code in articles"

### ISSUE THREAD

**Issue by dlepow** [MicrosoftDocs/Contribute#179]
Many of our Azure services support Docker containers in one way or the other, and we display either Docker CLI commands or Dockerfiles in code blocks. Would be useful to add to contributor guide (and support?) using code fences with `Docker` or `Dockerfile`

Based on a quick scan, some writers have already used code fences like ```Docker informally in their articles, although it isn't a supported language listed at https://review.docs.microsoft.com/en-us/help/contribute/code-in-docs?branch=master#supported-languages.

If this isn't the right place to consider this, please close or redirect. Thanks!

**Comment by nschonni** [comment]
`Dockerfile` at least is a supported language for GFM https://github.com/github/linguist/blob/58193319b3a1daa8fae0fec897029137a958568e/lib/linguist/languages.yml#L1075

**Comment by JasonWHowell** [comment]
Hi @dlepow, we confirmed ` ```Dockerfile `  is the right way to go 

Thanks, Jason
