### ISSUE TITLE
Mismatching date datatypes

### ISSUE THREAD

**Issue by thazanm** [MicrosoftDocs/Contribute#180]
In the following step:
8. On the Columns page, make the following selections:
            In the Available Input Columns panel, drag CurrencyDate to the Available Lookup Columns 
             panel and drop it on FullDateAlternateKey.

              In the Available Lookup Columns list, select the check box to the left of DateKey.

In the above step the data type for CurrencyDate  (database datetime [DB_DBTIME]) is not matching the column 'FullDateAlternateKey (date)'.

In order to avoid the data mismatch error the CurrencyDate  (database date[DT_DBDATE]) is working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/#create-quality-issues)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
HI @thazanm 

Are you referring to this [SSIS article](https://docs.microsoft.com/en-in/SQL/integration-services/lesson-1-6-adding-and-configuring-the-lookup-transformations?view=sql-server-2016). 

We don't currently have git issues feedback on that set of docs though. 

Thanks for the tip on what to update. I'll forward onto the right folks. 

Thanks, Jason
