### ISSUE TITLE
dhivyanshuparmhans all us 

### ISSUE THREAD

**Issue by Dhivyanshup** [MicrosoftDocs/Contribute#181]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e12137f-88e5-4fa2-5b7b-c62c5c5d1cc9
* Version Independent ID: 8cb8df2f-ee70-926f-2b58-edcfa285528f
* Content: [GitHub account setup steps - Contributor Guide](https://docs.microsoft.com/en-gb/contribute/get-started-setup-github)
* Content Source: [Contribute/get-started-setup-github.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/get-started-setup-github.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
Hi @Dhivyanshup looks like the feedback didn't get completely filled in. 

Let us know if you need assistance with something specific. Thanks, Jason
