### ISSUE TITLE
nodejs is a non-stardand language tag that should be deprecated

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/Contribute#182]
Unlike some of the extra tags that are unlikely to be accepted as regular GFM/Linguist language, the `nodejs` value should probably be deprecated and just be replaced with `javascript` everywhere.
Using the standard `javascript` tag gives support for GitHub and Visual Studio Code.
Currently the largest docset only has 39 files that use it https://github.com/MicrosoftDocs/azure-docs/pull/23076

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c11e26-0b4e-c922-1578-a487b16a7b7b
* Version Independent ID: 432d205a-c041-e6f7-0776-b13486fe2a1f
* Content: [How to use Markdown for writing Docs - Contributor Guide](https://docs.microsoft.com/en-ca/contribute/how-to-write-use-markdown)
* Content Source: [Contribute/how-to-write-use-markdown.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-use-markdown.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
Thanks @nschonni I talked it over with the right folk, and agree that its not a good idea to label code blocks as nodejs. Javascript is the preferred approach.

**Comment by nschonni** [comment]
Great to hear @JasonWHowell !
