### ISSUE TITLE
Support for terraform syntax highlighting

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/Contribute#188]
It looks like it's supported in GitHub markdown preview, but pages like https://docs.microsoft.com/en-ca/azure/terraform/terraform-create-vm-cluster-module don't have syntax highlighting for Terraform code blocks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c11e26-0b4e-c922-1578-a487b16a7b7b
* Version Independent ID: 432d205a-c041-e6f7-0776-b13486fe2a1f
* Content: [How to use Markdown for writing Docs - Contributor Guide](https://docs.microsoft.com/en-ca/contribute/how-to-write-use-markdown)
* Content Source: [Contribute/how-to-write-use-markdown.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-use-markdown.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rloutlaw** [comment]
I've added support for highlighting terraform scripts to our customer suggestion list. As it is written on the page-it's not there for  syntax highlighting , it's there for clarity on what the code block is.
