### ISSUE TITLE
Use compound code fences to enable syntax hightlighting

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/Contribute#193]
In the case of the custom code fence languages, if they are split out to separate words, then code hightlighting tools would work. This split words with hightlighting was something I saw over on the Azure Rest API specs so there is probably some logic alread for parsing code fences that way.
EX: 
with ```azurepowershell-interactive
```azurepowershell-interactive
$Sub1          = "&lt;YourSubscriptionName&gt;"
$RG1           = "TestPolicyRG1"
$Location1     = "East US 2"
$VNetName1     = "TestVNet1"
$FESubName1    = "FrontEnd"
$BESubName1    = "Backend"
$GWSubName1    = "GatewaySubnet"
$VNetPrefix11  = "10.11.0.0/16"
$VNetPrefix12  = "10.12.0.0/16"
$FESubPrefix1  = "10.11.0.0/24"
$BESubPrefix1  = "10.12.0.0/24"
$GWSubPrefix1  = "10.12.255.0/27"
$DNS1          = "8.8.8.8"
$GWName1       = "VNet1GW"
$GW1IPName1    = "VNet1GWIP1"
$GW1IPconf1    = "gw1ipconf1"
$Connection16  = "VNet1toSite6"

$LNGName6      = "Site6"
$LNGPrefix61   = "10.61.0.0/16"
$LNGPrefix62   = "10.62.0.0/16"
$LNGIP6        = "131.107.72.22"
```
vs. ```powershell azure-interactive
```powershell azure-interactive
$Sub1          = "&lt;YourSubscriptionName&gt;"
$RG1           = "TestPolicyRG1"
$Location1     = "East US 2"
$VNetName1     = "TestVNet1"
$FESubName1    = "FrontEnd"
$BESubName1    = "Backend"
$GWSubName1    = "GatewaySubnet"
$VNetPrefix11  = "10.11.0.0/16"
$VNetPrefix12  = "10.12.0.0/16"
$FESubPrefix1  = "10.11.0.0/24"
$BESubPrefix1  = "10.12.0.0/24"
$GWSubPrefix1  = "10.12.255.0/27"
$DNS1          = "8.8.8.8"
$GWName1       = "VNet1GW"
$GW1IPName1    = "VNet1GWIP1"
$GW1IPconf1    = "gw1ipconf1"
$Connection16  = "VNet1toSite6"

$LNGName6      = "Site6"
$LNGPrefix61   = "10.61.0.0/16"
$LNGPrefix62   = "10.62.0.0/16"
$LNGIP6        = "131.107.72.22"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c11e26-0b4e-c922-1578-a487b16a7b7b
* Version Independent ID: 432d205a-c041-e6f7-0776-b13486fe2a1f
* Content: [How to use Markdown for writing Docs - Contributor Guide](https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown)
* Content Source: [Contribute/how-to-write-use-markdown.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-use-markdown.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
@nschonni I don't know a lot about this subject, but not sure what your suggestion/question is. Seems like it would be ` ```azurepowershell-interactive `  What's the benefit you observed for splitting the words?

**Comment by nschonni** [comment]
Maybe the code sample about wasn't clear, but keeping the language (powershell) separate from your extra magic to make it interactive, then the code blocks are supported by IDEs and GitHub

**Comment by JasonWHowell** [comment]
@nschonni What's the use case you are thinking of? When do readers open docs in an IDE or in Github? Is it for editing the docs, or are there instances where readers would do that? It seems like a big change, and the use case isn't obvious to me.

**Comment by nschonni** [comment]
Editing/validation is probably the biggest part.
The other part is that the custom tags also don't line up with the actual language. EX: https://docs.microsoft.com/en-ca/azure/virtual-machines/windows/capture-image-resource the end tag is actually titled "Azure PowerShell" and adds the "Try it" button. I do also see other people (from seeing reported issues) that others also end up using GitHub search and view the docs here. The experience will never be 100% the same because the publishing platform adds a bunch of good stuff (like monikers & tabs), but using standard language tags where possible seems like a good thing.

There are some other tags that don't match up with the GH/IDE versions, but I don't want to side track this issue :wink:

**Comment by rloutlaw** [comment]
I'll mark this as a customer suggestion for internal triage and review.
