### ISSUE TITLE
No Edit button?

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/Contribute#198]
I have signed in, but dont see the Edit button. The page I want to contribute to is: https://docs.microsoft.com/en-us/dax/ln-function-dax

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-au/contribute/#create-quality-issues)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by otykier** [comment]
I'm facing the same issue. I want to edit this page: https://docs.microsoft.com/en-us/powershell/module/sqlserver/invoke-processasdatabase?view=sqlserver-ps

**Comment by JasonWHowell** [comment]
Reference content is generally not open to public edits, since there is automation behind the scenes that generates those pages from the source code and other upstream areas, so changes won't stick. 

For DAX, maybe @Minewiskan could take the feedback to the source. 
For SQL PowerShell, maybe @craigg-msft could advise where docs feedback could go. I'm not certain.

**Comment by Mike-Honey** [comment]
Fair enough. So can you edit this page to explain that, and stop us wasting our time?

**Comment by JasonWHowell** [comment]
@Mike-Honey  I'm making the updates now. We'll close out this thread. Thanks again for reporting the issue! Jason

**Comment by Triang3l** [comment]
@JasonWHowell Who can I send suggestions regarding Direct3D 12 reference pages to? They are missing some useful details that were there in D3D11 documentation (like MultisampleEnable/AntialiasedLineEnable meaning table missing from D3D12_RASTERIZER_DESC but there in D3D11_RASTERIZER_DESC, also ForcedSampleCount in D3D11_RASTERIZER_DESC1 reference had a good description of limitations, while in D3D12_RASTERIZER_DESC reference it's only a short vague sentence), and in some places they reference D3D11 articles/names (ID3D12GraphicsCommandList::OMSetBlendFactor and something else I forgot), and also there are pages where some data is incorrect. The possible values for D3D12_RASTERIZER_DESC::ForcedSampleCount include 2 as mandatory, however, it's optional and not supported on Nvidia (in D3D11_FEATURE_DATA_D3D11_OPTIONS documentation 2 isn't listed though, but in D3D11_RASTERIZER_DESC1 reference it's also incorrectly listed). Another issue is null RTV descriptor usage covered in ID3D12Device::CreateRenderTargetView — I'm not completely sure, but it seems like null RTV descriptors are not usable in D3D12 at all, a few months ago I tried different combinations of DXGI_FORMAT_UNKNOWN set in different places for render targets with no success, though maybe this needs to be investigated deeper. On a somewhat unrelated note, there's a bug in d3d12.h itself that corrupts the stack if you use certain functions from lpVtbl (that's the only way to access them in the C language) — lpVtbl methods (and their respective ID3D12Something_Method shortcut #defines), such as ID3D12DescriptorHeap_GetCPU/GPUDescriptorHandleForHeapStart and ID3D12Resource_GetDesc, must not return struct types, instead they must take an _Out_ pointer to the target structure as the last argument.

**Comment by JasonWHowell** [comment]
@Triang3l 
Windows topics are unrelated to SQL PowerShell / DAX.  Reference documentation is machine generated, and I don't have a contact in that department. I'll ask around if anyone knows on my team. 

Thanks, Jason

**Comment by JasonWHowell** [comment]
@Triang3l I found a contact @stevewhims and he will follow-up on your request. Thanks for raising it to our attention. Thanks, Jason
