### ISSUE TITLE
Example not working in "Audience Counts"

### ISSUE THREAD

**Issue by mbiagetti** [MicrosoftDocs/Contribute#217]
I found a typo in an example of the page https://docs.microsoft.com/en-us/linkedin/marketing/integrations/ads/advertising-targeting/audience-counts

But no edit button appear (I made the login)

How can I contribute?

The fix is to transform in uppercase na --&gt; NA in the following string ```3AcountryGroup%3Ana))),(or```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
@mbiagetti That repo isn't open for edits. We can look at the contributors at the top of the page, and ping the author (there's a tag for author that in the metadata). 
@abarron-linkedin Could you fix the typo?

**Comment by mbiagetti** [comment]
Thanks @JasonWHowell for the feed. I see also @aelkunch is a contributor of that page.

How can I contribute to that docs? I also have a lot of dubt on other section of the doc related to LinkedIn ads API (specially for the target section), how can I submit some question related to it (like the [Facebook Developer Support](https://developers.facebook.com/support/))?

**Comment by abarron-linkedin** [comment]
@mbiagetti Thank you for the feedback. I've filed a ticket to address that typo.

For your other questions, we do offer developer support to approved developers for our Marketing Developer Platform. If you've already applied to this, you will have been provided a link to the support form. Please send future questions and feedback through that portal.

If you haven't applied to the program, you can do so here: https://business.linkedin.com/marketing-solutions/marketing-partners/become-a-partner/marketing-developer-program
