### ISSUE TITLE
Wrong example in "targetingCriteria Examples" LinkedIn Ads API Page

### ISSUE THREAD

**Issue by mbiagetti** [MicrosoftDocs/Contribute#219]
The [Object “includes” all users in California , “excluding” users who are “Managers”.](https://docs.microsoft.com/en-us/linkedin/shared/references/v2/ads/targeting-criteria-examples#this-object-includes-all-users-in-california--excluding-users-who-are-managers) Example is wrong because don't respect the first rule:

 - The include object contains a single encompassing array object called “and” .

Defined in the page [targetingCriteria Object](https://docs.microsoft.com/en-us/linkedin/shared/references/v2/ads/targeting-criteria?context=linkedin/marketing/context#rules).

The fix should be:
```
{
	"include": {
		"and": [{
			"or": {
				"urn:li:adTargetingFacet:locations": [
					"urn:li:state:(urn:li:country:us,CA)"
				]
			}
		}]
	},
	"exclude": {
		"or": {
			"urn:li:adTargetingFacet:seniorities": [
				"urn:li:seniority:5"
			]
		}
	}
}
```

Tested using the API in order to create an Ads Campaign

**Comment by JasonWHowell** [comment]
@abarron-linkedin Could you please address this concern, or followup offline as needed?

**Comment by abarron-linkedin** [comment]
@mbiagetti Thank you for the feedback. I've filed a ticket to address that issue.

For your other questions, we do offer developer support to approved developers for our Marketing Developer Platform. If you've already applied to this, you will have been provided a link to the support form. Please send future questions and feedback through that portal.

If you haven't applied to the program, you can do so here: https://business.linkedin.com/marketing-solutions/marketing-partners/become-a-partner/marketing-developer-program
