### ISSUE TITLE
What does Missing Edit actually imply?

### ISSUE THREAD

**Issue by bilbothebaggins** [MicrosoftDocs/Contribute#225]
OK, so I get that "If the Edit button (pencil icon) is missing, that means the documentation page is not available to be changed.", but what does that ACTUALLY mean? Has this part of the docs not been transitioned to GitHub (yet?)? Does MS not wish feedback on that part of the docs? How can - or should? - I request - or provide - a doc fix on a docs page that cannot be Edited and that has no feedback option?

To wit: https://docs.microsoft.com/en-us/windows/desktop/com/runas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/#feedback)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by bilbothebaggins** [comment]
OK: https://github.com/MicrosoftDocs/Contribute/issues/198 explains that "Reference content is generally not open to public edits, since there is automation behind the scenes that generates those pages from the source code and other upstream areas, so changes won't stick."

And this explains that I cannot contribute by Editing. How else should one give feedback on wrong information on these pages? Didn't the old msdn have a comment section to the articles?

**Comment by JasonWHowell** [comment]
@MicrosoftDocs/windows-authoring  in case anyone knows from the Windows doc team.

**Comment by mijacobs** [comment]
@bilbothebaggins Some of our API reference docs do supporting editing (see our WinRT docs). When the edit button is missing, it means that public contributions aren't enabled for that content. When a documentation set doesn't support editing or issues, it means that we haven't hooked up the contribution mechanisms that support editing yet, or we're unable to process content edits and/or GitHub issues for that content (we don't want to ask for issues or contributions unless we can respond to them in a timely manner), or the content is considered archived and we're not publishing updates. (This is the case for the content in our "Previous versions" archive.) 

Public contributions for this particular content might be enabled at some point in the future, but I don't have a date.

**Comment by JasonWHowell** [comment]
@bilbothebaggins Hope this thread helped some. I'll resolve the thread for now, but if you need other input please let us know. Thanks, Jason
