### ISSUE TITLE
The content for the tab-group-invalid rule is empty

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/Contribute#230]
It just has 2 backticks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa011899-ac62-20f9-2292-150c8bfcbe03
* Version Independent ID: 22c24db2-daf0-c71c-08f9-98f81e1b13ba
* Content: [tab-group-invalid - Contributor Guide](https://docs.microsoft.com/en-us/contribute/validation-reference/tab-group-invalid)
* Content Source: [Contribute/validation-reference/tab-group-invalid.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/validation-reference/tab-group-invalid.md)
* Product: **non-product-specific**
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by JasonWHowell** [comment]
@meganbradley please take a look when you have a chance.

**Comment by meganbradley** [comment]
@JasonWHowell @nschonni thanks - I've removed the file until we're ready for it. Change should go live shortly.
