### ISSUE TITLE
The output of the example provided for CalendarAuto  DAX  is incorrect.

### ISSUE THREAD

**Issue by PrakiP** [MicrosoftDocs/Contribute#243]

**Comment by PrakiP** [comment]
![image](https://user-images.githubusercontent.com/49586629/56078888-a4dad700-5e0a-11e9-9dab-2865249b3d7c.png)

**Comment by JasonWHowell** [comment]
Hi @PrakiP, 

Which article are you referring to?

Curious how did you reach the issues page. Link, search, or something else? It’s not related to DAX so trying to understand in case our feedback links are misconfigured. 

Thanks, Jason

**Comment by JasonWHowell** [comment]
@Minewiskan is this something you can look at briefly? Thanks, Jason
