### ISSUE TITLE
windows/desktop changes

### ISSUE THREAD

**Issue by tiagomacarios** [MicrosoftDocs/Contribute#247]
Where can I edit documentation under windows/desktop. for example: https://docs.microsoft.com/en-us/windows/desktop/debug/using-a-vectored-exception-handler ?
I cannot find that content here on GitHub.

**Comment by JasonWHowell** [comment]
Hi @tiagomacarios 

Not all docs are open source in GitHub, and it looks like the page you landed on is not available for public edits.

The authors listed are @GrantMeStrength and @msatranjr in case you want to contact them for discussion though. 

Thanks, Jason
