### ISSUE TITLE
Broken and missing links

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/Contribute#25]
Broken links in the localized documentation section 

Also, this page should probably link to Microsoft's main style guide published on docs (docs.microsoft.com/style-guide)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1ae7b8-3034-5991-b141-e6f94136be95
* Version Independent ID: f6dc9cb7-589f-de11-0b54-ad8a9394d66f
* Content: [Docs Style guide - Quick start - Contributor Guide](https://docs.microsoft.com/en-us/contribute/style-quick-start)
* Content Source: [Contribute/style-quick-start.md](https://github.com/MicrosoftDocs/Contribute/blob/live/Contribute/style-quick-start.md)
* Service: **unspecified**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BryanLa** [comment]
Adding @MonicaRush for visibility.
