### ISSUE TITLE
do we really need this page?

### ISSUE THREAD

**Issue by meganbradley** [MicrosoftDocs/Contribute#251]
It's pretty much completely redundant with the Markdown reference below it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c11e26-0b4e-c922-1578-a487b16a7b7b
* Version Independent ID: 432d205a-c041-e6f7-0776-b13486fe2a1f
* Content: [How to use Markdown for writing Docs - Contributor Guide](https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown)
* Content Source: [Contribute/how-to-write-use-markdown.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-use-markdown.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
I think we have a workitem, around 6 months back. @SyntaxC4 any updates? Re 1291216

**Comment by mairaw** [comment]
Some information only lives in this page and not in the other.
https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown#code-snippets

So make sure that we don't delete this page without merging missing info from the other.

**Comment by pennyo** [comment]
It's also the only place that has a link to an example of selectors, which is handy when trying to figure out how to use them. The selector reference doc doesn't contain enough information. It shows you the syntax but has no info on whether/how to link to something through a selector. The example link on this page at least gives us a repo to look at so we can figure this out.

**Comment by Jim-Parker** [comment]
Assigned to @tdykstra

**Comment by Rick-Anderson** [comment]
The OPS build warnings point to this page. Update the fwlink when you delete this page.

**Comment by tdykstra** [comment]
What's the link id?

**Comment by Rick-Anderson** [comment]
The legacy code snippet inclusion will be deprecated at a later date. Please use the new code extension. (http://aka.ms/codesnippet)
