### ISSUE TITLE
woud like to provide feedback for doc.microsoft article 

### ISSUE THREAD

**Issue by v-sulee** [MicrosoftDocs/Contribute#256]
Hi, I would like to provide feedback for article, (https://docs.microsoft.com/en-us/partner-center/faq-about-new-billing-features). Some figures might need to be corrected to deliver the correct information. May I know how I can go about doing that?

**Comment by nschonni** [comment]
It's not clear on the sites that don't have the feedback enabled, but https://github.com/MicrosoftDocs/feedback/issues is probably a better place to file an issue for a content issue

**Comment by v-sulee** [comment]
thanks! I will submit a new issue over there

**Comment by JasonWHowell** [comment]
Feedback is disabled in some doc areas where the team is not ready to triage the feedback, or where automated systems produce the reference content. You can see the contributors names at the top of the article, and start an issue with them individually I suppose. For example, @MaggiePucciEvans could point you in a direction on that article.  Thanks, Jason
