### ISSUE TITLE
downloadable pdf is  much appreciated

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/Contribute#262]
Every time we can't go online  for reading this guide, so if possible downloadable pdf content is much appreciated to all users and users can able to read offline.
Required contributor user guide.

Thanks for this article to all authors 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-in/contribute/#feedback)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
Hi @RAJU2529 

I turned on PDF for this guide. Thanks for the suggestion. 
https://docs.microsoft.com/en-us/contribute/

~Jason
