### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by popujol** [MicrosoftDocs/Contribute#263]
This page explain how to free-up some space, which is very good.
However if users are storing activities with big files, we cannot just delete them. It would be interesting to advise how the same heavy files could be stored in Azure nblob or sharepoint and how to migrate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/#feedback)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
Sorry there isn't enough information to assist you here. 

You're better off to use the MSDN forums for more specific help on an Azure service. 
https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazuredata

Thanks, Jason
