### ISSUE TITLE
Provide example of Code snippets

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/Contribute#287]
Could you provide an example of the Code snippet usage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd2bb3d-3104-1be7-7232-8a194074af4b
* Version Independent ID: 2efecbe2-8538-8659-7740-6f8852f7875b
* Content: [Markdown reference for docs.microsoft.com - Contributor Guide](https://docs.microsoft.com/en-us/contribute/markdown-reference#code-snippets)
* Content Source: [Contribute/markdown-reference.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/markdown-reference.md)
* Product: **non-product-specific**
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by meganbradley** [comment]
@docs-product FYI - thanks!

**Comment by Jim-Parker** [comment]
@docs-product can you take a look at this?

**Comment by Jim-Parker** [comment]
@tdykstra FYI

**Comment by Jim-Parker** [comment]
@tdykstra has this issue been addressed by the changes you made?

**Comment by tdykstra** [comment]
Yes

**Comment by Jim-Parker** [comment]
@baardhermansen this issue was addressed in PR358. I'm closing this issue. Let me know if you have any concerns.
