### ISSUE TITLE
What does it do? Repo availability #sign-off

### ISSUE THREAD

**Issue by 40345839668** [MicrosoftDocs/Contribute#292]
What does it do?
Repo availability
#sign-off
When the author of an article writes a comment in the comment feed, a label ready to merge is assigned. This label lets reviewers in the repo know that the withdrawal request is ready for review/combined time. If a non-author participant tries to sign a public repo withdrawal request using the comment, a message will be written to the withdrawal request stating that only the author can assign the tag. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c68d84b-6a64-722b-bf11-78d6e1009c4b
* Version Independent ID: 3b4e7a64-72d4-b6b0-2c23-bb2b0017becf
* Content: [GitHub contribution workflow for major or long-running changes - Contributor Guide](https://docs.microsoft.com/en-us/contribute/how-to-write-workflows-major#feedback)
* Content Source: [Contribute/how-to-write-workflows-major.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-workflows-major.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
@40345839668  I don't fully understand the question here, but let me try:

#sign-off is a signal that you are done editing / iterating, and its time for someone at Microsoft to review and merge.

**Comment by nschonni** [comment]
I thought `#sign-off` is only done by the article author to indicate that they are OK with the PR, and the bot should change the label to "ready-to-merge"

**Comment by JasonWHowell** [comment]
@nschonni correct, when that automated system is enabled, which is not universal. I'm not sure what the original question is though. Maybe your extra context resolved the question.

**Comment by JasonWHowell** [comment]
@40345839668 Hope this thread answers the question. We'll close it out for now, but let us know if you need further clarification.
