### ISSUE TITLE
Type on Z-Order page

### ISSUE THREAD

**Issue by zaqwer777** [MicrosoftDocs/Contribute#30]
I was unable to find any edit/feedback on the page. "By using the options in the Arrange button menu, you can get the ordering of elements on you report just the way you want it." There is a type in the "you report" area, which I believe was intended to be "your report".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/live/Contribute/index.md)
* Service: **unspecified**
* Product: **non-product-specific**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by DuncanmaMSFT** [comment]
Hey @zaqwer777 I'll get this feedback to the right person, but can you help me find the page you were talking about?

**Comment by BryanLa** [comment]
FYI for @MonicaRush

**Comment by mairaw** [comment]
I've created a PR to fix this. It was on the following article: https://docs.microsoft.com/en-us/power-bi/guided-learning/visualizations?tutorial-step=17.

**Comment by JasonWHowell** [comment]
@zaqwer777 Thanks for the feedback. Appreciate your eye for detail.

I'll close it out now, since @mairaw has fixed it. 

Thanks, Jason
