### ISSUE TITLE
Missing precision about how to relate a Doc page to a Github repository

### ISSUE THREAD

**Issue by Joacchim** [MicrosoftDocs/Contribute#324]
Hello,

If I understand this page correctly, one should be able to contribute to the open-source docs from Microsoft  through a github workflow, but not all documentation pages from Microsoft are related to a github public repository.

As such, I personally believe that it would be of great value for potential contributors to explain in this page how to:
1. Differenciate a public-repository documentation page from a private-repository documentation page
2. Tell how to find the repository for any given public-repository documentation page (it can be the buttons previously mentionned, but I could not see it on the doc page I was looking at, which led me here)
3. Give a clear and explicit means of contacting Microsoft for private-repository documentation feedback and suggestions.

To clarify my point: I'm looking at https://docs.microsoft.com/fr-fr/windows/win32/api/minwinbase/ns-minwinbase-win32_find_dataa with my team, due to a bug generated by blindly following a formula suggested by the doc:
```
nFileSizeHigh

The high-order DWORD value of the file size, in bytes.
This value is zero unless the file size is greater than MAXDWORD.
The size of the file is equal to (nFileSizeHigh * (MAXDWORD+1)) + nFileSizeLow.
```

The specific formula created a constant overflow as explained in https://stackoverflow.com/questions/15209077/finding-correct-filesize-over-4gb-in-windows, and as such, we had the intent to suggest a slight update to this formula and documentation, to prevent other users from encountering the same issue.

I'd welcome any description of the process to follow, to make our proposal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/#feedback)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @Joacchim, this doc set now supports public contributions through GitHub. Look for the edit button near the top of the article. Let us know if you still have any issues with the process.
