### ISSUE TITLE
Adding content to the right side navigation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Contribute#33]
How can we add items to the right side navigation (under In this article?)  can those navigation headings be formatted/indented/grouped?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcff0d60-cd99-d88d-9e21-bee20c17a4de
* Version Independent ID: ff9c4a5e-f283-9c95-b8fb-a3adb87460cc
* Content: [How to use links in documentation - Contributor Guide](https://docs.microsoft.com/en-us/contribute/how-to-write-links#links-in-selectors)
* Content Source: [Contribute/how-to-write-links.md](https://github.com/MicrosoftDocs/Contribute/blob/live/Contribute/how-to-write-links.md)
* Product: **non-product-specific**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BryanLa** [comment]
Hi @DeanGross - the right nav items are auto-generated, based on the level 2 headings in the page (ie: lines that start with `##`). Outside of the text you use in the headings, there is no other formatting control we have over them. HTH.

FYI for @MonicaRush

**Comment by DeanGross** [comment]
Ok, thanks, on really long pages it would be great if we could get the level 3 headings to show up also. I guess as a workaround the Level 3's could be changed from starting with  ### to ##

**Comment by JasonWHowell** [comment]
@DeanGross Hope your question was answered. I'm closing out this thread now, but let us know if more help is needed. Thanks, Jason
