### ISSUE TITLE
Migration cannot be used with version 6.3 of EntityFramework

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/Contribute#330]
Hi team, 
I moved this from here:  https://github.com/MicrosoftDocs/Contribute.ja-JP/issues/10
@kantoexp commented 18 hours ago — with docs.microsoft.com
Migration does not work with version 6.3 of EntityFramework. Please improve it 
as soon as possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/#feedback)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by nschonni** [comment]
Think this is probably something for https://github.com/aspnet/EntityFramework6 rather than Contribute

**Comment by BillWagner** [comment]
@CeciAc Can you move this issue to the EntityFramework6 repository, per the comment above?

**Comment by CeciAc** [comment]
moved to https://github.com/aspnet/EntityFramework6/issues/1505
