### ISSUE TITLE
C# Linq 101 samples page is Unavailable in MSDN

### ISSUE THREAD

**Issue by MdMudassirHussain** [MicrosoftDocs/Contribute#331]
This was the [link](http://code.msdn.microsoft.com/101-LINQ-Samples-3fb9811b) to learn C# Linq 101 samples in MSDN but now it redirects some other page. I'm unable to find C# 101 samples. Anybody has any idea? Was this a mistake from Microsoft's end?

**Comment by BillWagner** [comment]
These samples have been moved and updated to use the new .NET Core "dotnet try" experience.

You can find them here: https://github.com/dotnet/try-samples
