### ISSUE TITLE
Translation Related

### ISSUE THREAD

**Issue by kongxiangyan** [MicrosoftDocs/Contribute#334]
Hey, guys! I have notice that some of the document doesn't have a Chinese Version. I want in and do some document translate stuff for community. How can I get to do that, I can't find any words about it in docs. Maybe you guys can give me some guidence, thanks ! ! !

**Comment by JasonWHowell** [comment]
@SonjaSaltzman could you take a look at this request, please.

**Comment by SonjaSaltzman** [comment]
Hello @kongxiangyan ! Our official guidelines are posted here: https://docs.microsoft.com/zh-cn/contribute/ .  As the article mentions, not all content is open to contribution.  If you would like to request to have specific articles translated, please open a GitHub issue on the English article; for example, if you would like this topic https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sql/virtual-machines-windows-sql-server-iaas-overview translated to some not-yet-existing language, you could open a GitHub issue by requesting translation by clicking this button:  
![image](https://user-images.githubusercontent.com/15201704/71685734-0ef72b80-2d4e-11ea-9c44-96027499b7f2.png) and requesting translation.
cc @SunnyDeng

**Comment by Jim-Parker** [comment]
@kongxiangyan do you have any additional questions or concerns before we close this?

**Comment by kongxiangyan** [comment]
Thanks for your reply! It's pretty helpful to tell me that I can contribute in some way! I have no problem now.
