### ISSUE TITLE
Schema namespace references cannot use http - causes unnecessary warnings

### ISSUE THREAD

**Issue by VesaJuvonen** [MicrosoftDocs/Contribute#338]
In SharePoint dev docs we have roughly 500 files with xml namespace reference and as these are locked strings in the SharePoint product, we cannot change the text in the md file to be https - as that would not work.

Example case would be https://github.com/SharePoint/sp-dev-docs/blob/master/docs/schema/identities-element-in-subscription-subscription-schema.md which has a namespace reference of http://schemas.microsoft.com/office/2006/03/BusinessDataCatalog which is NOT a real link - rather a string which is used in the product... and changing it to use https which break things.

So - unless there's any way to avoid strings with "http" to not get translated as links, we cannot follow up on this documentation guidance which will then result hundreds of warnings in each time when we publish something.

Any advice would be appreciated to lean up the publish report. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0294f691-1792-18c1-5eb4-a0fb7b0b5541
* Version Independent ID: a87a7506-8790-144f-4163-1046d1981722
* Content: [insecure-link - Contributor Guide](https://docs.microsoft.com/en-us/contribute/validation-reference/insecure-link#feedback)
* Content Source: [Contribute/validation-reference/insecure-link.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/validation-reference/insecure-link.md)
* Product: **non-product-specific**
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by meganbradley** [comment]
@VesaJuvonen the solution for anything that isn't meant to be a real link is to style it as inline code:

`http://schemas.microsoft.com/office/2006/03/BusinessDataCatalog`

**Comment by VesaJuvonen** [comment]
Thanks - got things sorted out with the formatting changes.
