### ISSUE TITLE
DAX MID function in MSDN documentation

### ISSUE THREAD

**Issue by az38** [MicrosoftDocs/Contribute#347]
Hi!
According the [MSDN](https://docs.microsoft.com/en-us/dax/mid-function-dax?source=docs) this statement is correct:
`=MID([ResellerName,5]) `
` the second example omits the table name and the parameter, num_chars.`

for me none of statements don't work
```
=MID([Column,5])
=MID([Column;5])
=MID([Column];5)
```
The error always the same
> Too few arguments were passed to the MID function. The minimum argument count for the function is 3.

[DAX.Guide](https://dax.guide/mid/) doesn't say anything about this option as well

Looks like incorrect MSDN docs

**Comment by Jim-Parker** [comment]
@az38 Thanks for filing this issue. I’ve contacted @Minewiskan (who is the owner for this content). I’m going to close this issue because feedback here is for the contributor guide articles. For issues with DAX content please use https://github.com/MicrosoftDocs/feedback/issues.
