### ISSUE TITLE
DAX DATEDIFF function in MSDN documentation

### ISSUE THREAD

**Issue by az38** [MicrosoftDocs/Contribute#352]
It's need to remove remark "An error is returned if start_date is larger than end_date." from here https://docs.microsoft.com/en-us/dax/datediff-function-dax according https://dax.guide/datediff/

**Comment by nschonni** [comment]
Probably needs to move over to https://github.com/MicrosoftDocs/sql-docs

**Comment by az38** [comment]
> Probably needs to move over to https://github.com/MicrosoftDocs/sql-docs

I’m not sure, I was sent here from power bi community

**Comment by Jim-Parker** [comment]
@az38 Thanks for filing this issue. I’ve contacted @Minewiskan (who is the owner for this content). I’m going to close this issue because feedback here is for the contributor guide articles. For issues with DAX content please use https://github.com/MicrosoftDocs/feedback/issues.
