### ISSUE TITLE
DAX UNICODE function in MSDN documentation

### ISSUE THREAD

**Issue by az38** [MicrosoftDocs/Contribute#354]
Hi!
There is a legacy function CODE in MSDN docs: https://docs.microsoft.com/en-us/dax/code-function-dax
And there is no UNICODE function page which is actual according https://dax.guide/unicode/

**Comment by Jim-Parker** [comment]
@maggiesMSFT is there a better place for this and the 2 related issues since they are not contributor guide related?

**Comment by Jim-Parker** [comment]
@az38 Thanks for filing this issue. I’ve contacted @Minewiskan (who is the owner for this content). I’m going to close this issue because feedback here is for the contributor guide articles. For issues with DAX content please use https://github.com/MicrosoftDocs/feedback/issues.
