### ISSUE TITLE
fix typo

### ISSUE THREAD

**Issue by phateskimo** [MicrosoftDocs/Contribute#360]
"on-premise" should be "on-premises"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/#feedback)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
Hi @phateskimo 
Thanks for the feedback. I can't seem to find the word you referenced. Do you recall the page where you saw "on-premise"? or was it just a general statement for doc pages in general?

Thanks, Jason
