### ISSUE TITLE
Ampersand html encoded in source code example

### ISSUE THREAD

**Issue by justintaft** [MicrosoftDocs/Contribute#363]
The page https://docs.microsoft.com/en-us/previous-versions/windows/desktop/proc_snap/export-a-process-snapshot-to-a-file contains '&amp;' in a source code snippet. It should read `&` instead.

```
HANDLE SnapshotHandle;
DWORD dwResultCode = PssCaptureSnapshot (ProcessHandle,
                                         CaptureFlags,
                                         CONTEXT_ALL,
                                         &amp;SnapshotHandle);

// Error handling omitted. Check that dwResultCode is ERROR_SUCCES
```

There was another page where inside the text a backslash `\` did not appear at all when describing characters, ie the text read `()` instead of `(\)`.  I don't recall the page at this time.

**Comment by Jim-Parker** [comment]
@justintaft thank you for the suggestion. However, this content is in an "archived state", so we're not updating the information any longer.
