### ISSUE TITLE
Need reference/example on video link format

### ISSUE THREAD

**Issue by jaimeo** [MicrosoftDocs/Contribute#364]
Neither this page, nor the dedicated topic on "Links" it refers to, offer any information about the format of links to videos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd2bb3d-3104-1be7-7232-8a194074af4b
* Version Independent ID: 2efecbe2-8538-8659-7740-6f8852f7875b
* Content: [Markdown reference for docs.microsoft.com - Contributor Guide](https://docs.microsoft.com/en-us/contribute/markdown-reference#feedback)
* Content Source: [Contribute/markdown-reference.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/markdown-reference.md)
* Product: **non-product-specific**
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by Jim-Parker** [comment]
@jaimeo I'm closing this and will follow up in email.
