### ISSUE TITLE
Add guidance on how to deal with unavoidable "http"

### ISSUE THREAD

**Issue by jaimeo** [MicrosoftDocs/Contribute#365]
The Important note above is correct that the "vast majority" of links should be https:--but there are a few definitely unavoidable exceptions. This topic should provide guidance on what to do with those. (The suggested solution is to style them as inline code with backticks.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcff0d60-cd99-d88d-9e21-bee20c17a4de
* Version Independent ID: ff9c4a5e-f283-9c95-b8fb-a3adb87460cc
* Content: [How to use links in documentation - Contributor Guide](https://docs.microsoft.com/en-us/contribute/how-to-write-links)
* Content Source: [Contribute/how-to-write-links.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-links.md)
* Product: **non-product-specific**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Jim-Parker** [comment]
@gewarren can you take a look at this and address as required? Thanks

**Comment by gewarren** [comment]
@jaimeo Are you suggesting to style the links as inline code to avoid validation problems? If it's styled as inline code, then the link won't work.

If your question is more about example URLs instead of functional links, then this page might not be the right place to incorporate that guidance.

**Comment by jaimeo** [comment]
Yes.

The scenario in which I encountered this problem is a list of endpoints that must be whitelisted for updates to work. They are not website URLs that anyone would be clicking to follow. Certain of the endpoints must be http:// (they will not work if https://), but this freaks out our validation.

I’ll leave it to you where the best place to incorporate this guidance might be, but it needs to be incorporated somewhere. This place made sense to me because it’s the only place I know of where “links” and formatting of same are mentioned at all. The guidance can make it clear when it’s appropriate to do this.

Thanks,
vv
J.O.

**Comment by gewarren** [comment]
The validation reference already includes that guidance (see the last sentence of [this section](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/insecure-link?branch=master)), so I think this issue can be closed.

**Comment by jaimeo** [comment]
That’s nice, but wouldn’t it be a better user experience to let authors know to do this before they get a bunch of errors and have to go hunt up what the problem is? I mean, that is the point of a reference guide.

vv
J.O.
