### ISSUE TITLE
Docs Content Validation's page is removed

### ISSUE THREAD

**Issue by hsebs** [MicrosoftDocs/Contribute#374]
[Docs Content Validation](https://github.com/apps/docs-content-validation) uses https://docs.microsoft.com/en-us/contribute/validation-reference/ as it's website.

**Comment by Jim-Parker** [comment]
@meganbradley can you look into this?

**Comment by Jim-Parker** [comment]
@hsebs can you tell me a little more about this issue, so I understand what solution to provide?

**Comment by meganbradley** [comment]
This app is deprecated and will be removed soon. I'm just trying to warn the various repo owners before I remove it.

**Comment by Jim-Parker** [comment]
@hsebs per @meganbradley I think we can close this. The app that links to the validation ref page will be removed.
