### ISSUE TITLE
There is a misspelling

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/Contribute#381]
See "Allow all members to contribute is On: Members of the group are contributors, so owners and members of the group will have ownershiop of the video."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/#feedback)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by raydixon** [comment]
This is not linked to the page that contains the content with the typo. Below is the correct information.

* ID: 3485fe60-37e8-8780-7a8c-5eccf2b09ae4
* Version Independent ID: 2a35388b-fe30-534d-b39c-d5d97275fc9c
* Content: [Permissions and privacy in Microsoft Stream"](https://docs.microsoft.com/en-us/stream/portal-permissions)
* Content Source: [streamdocs/portal-permissions.md](https://github.com/MicrosoftDocs/stream-docs-pr/blob/live/stream-docs/portal-permissions.md)
* Product: **MSDN**

I couldn't find information in the page source for GitHub Login and Microsoft Alias.

**Comment by Jim-Parker** [comment]
We've filed a PR to fix this. Thank you for catching that mistake.
