### ISSUE TITLE
Information on this page appears inconsistent with CONTRIBUTE.md

### ISSUE THREAD

**Issue by brcaswell** [MicrosoftDocs/Contribute#384]
the [CONTRIBUTION](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md) file references to [https://docs.microsoft.com/contribute/](https://docs.microsoft.com/contribute/) being the new guidance, but this page is not consistent or updated\maintained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de333629-fa39-19eb-37f7-9b1e186a549e
* Version Independent ID: cb8fb2f4-b353-a7dd-cd75-fca323eb60f8
* Content: [Contribution process for .NET docs repositories - Contributor Guide](https://docs.microsoft.com/en-us/contribute/dotnet/dotnet-contribute-process)
* Content Source: [Contribute/dotnet/dotnet-contribute-process.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/dotnet/dotnet-contribute-process.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by brcaswell** [comment]
Also, there is a mention in that file to an overarching effort to\of consistency, but I don't see labels or milestones in this project that could be used for designations of inconsistency, or that could otherwise facilitate the effort.

**Comment by BillWagner** [comment]
I think #377 by @tdykstra addresses this.

I recommend closing it.

**Comment by brcaswell** [comment]
Though I think that linked, merged PR \ MR and the closed issue that merited the PR are relevant to the overarching effort.   I don't think it addresses the inconsistencies of the Content Source to the CONTRIBUTE file content.  

In particular (and I suppose we should be particular here) the 'DO's and DONT's` sections are not the same, nor of the same count.
