### ISSUE TITLE
[Win32 UIRibbon]Need example or documentation on the DynamicUI markup element

### ISSUE THREAD

**Issue by rikka0w0** [MicrosoftDocs/Contribute#387]
I was trying to add commands and buttons during runtime, the win32 ribbon framework (UIRibbon.dll) does not seem to support this. However, I found that the documentation mentioned the DynamicUI markup element. It was described as "Represents a container for Ribbon markup. This container and its content is declared at run time." Unfortunately, I cannot find any example or more detailled documentation on this.

https://docs.microsoft.com/en-us/windows/win32/windowsribbon/windowsribbon-element-dynamicui

Has any one use this feature before?

Also, is there any documentation about the binary file generated by UICC.exe? I reverse-engineered its format, but I'm still looking forward to see the official documentation.

Thanks in advance!

**Comment by rikka0w0** [comment]
One more question, am I allowed to make the binary format available to the public?

**Comment by Jim-Parker** [comment]
@rikka0w0 it looks like you're already getting help on the forum. I'm closing this as a duplicate effort. Thank you.
