### ISSUE TITLE
[Azure-DevOps] PR Files / Code Review no longer shows Total Files (1/10 Reviewed) same for comments

### ISSUE THREAD

**Issue by antoinecfmws** [MicrosoftDocs/Contribute#392]
Hello,

We switched recently to the new UI for Azure DevOps but we lost an important feature and that is seeing how many files are remaining to review. It used to show on the top bar at the same level as Overview / Files / Updates / Commits.

Same for the comments it used to show 1/5 comments resolved. 

It is a very important feature for us to guage how far a PR is from being completed / reviewed.

Is it possible to switch to the old ui? 

Thank you!

**Comment by nschonni** [comment]
I'd suggest trying over https://github.com/MicrosoftDocs/azure-devops-docs

**Comment by antoinecfmws** [comment]
Thanks for the suggestion, I just gave it a try and they seem to be redirecting these kind of issues to the Azure Devops community stie.

> Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Closing for now. Cheers.
