### ISSUE TITLE
Choosing Learning Paths > Dynamics 365 > Select Your Role -> Solution Architect leads to a 404 error page

### ISSUE THREAD

**Issue by philstubbington** [MicrosoftDocs/Contribute#395]
From https://docs.microsoft.com/en-us/learn/dynamics365/ .....choosing Learning Paths > Dynamics 365 > Select Your Role -> Solution Architect leads to a 404 error page

**Comment by Jim-Parker** [comment]
@philstubbington We're having trouble reproing the issue. Can you tell us if you went to the hub page and used the "Select your role" dropdown? Or, did you go to the browse page and filter by Dynamics+Solutions Architect to get to the content?

**Comment by philstubbington** [comment]
@Jim-Parker I went to the link shown above, scrolled down to "Select your role", chose "Solution Architect" and got the 404 here:-

https://docs.microsoft.com/en-us/browse/?roles=solution-architect&products=dynamics

**Comment by Jim-Parker** [comment]
Thanks @philstubbington . We were able to repro. I'm adding @barlan to this issue. He's filing a bug to get the link fixed.

**Comment by barlan** [comment]
The fix is live on the site now! Thanks @philstubbington for calling it out.

**Comment by philstubbington** [comment]
You’re welcome @barlan :) Helping where I can!

**Comment by Jim-Parker** [comment]
Closing as resolved.
