### ISSUE TITLE
Confusion in a training module

### ISSUE THREAD

**Issue by georgiebrown10** [MicrosoftDocs/Contribute#396]
I am doing training module https://docs.microsoft.com/en-gb/learn/modules/build-power-app-component/1-create-code-component
In the Implement your code component's logic section, I am not sure where I am supposed to be for this.  To implement your code component's logic, follow these steps:
1.Open your code component.
2.Above the constructor method, insert the following private variables:
Please can this be updated to give more detail?  I am not sure whether I should be in Visual Studio Code still, and if so, how I open the code component and what the code component actually is.  I was referred to this site by the Microsoft Support team for this call 2005070050000275 CW.
Georgie
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-gb/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Jim-Parker** [comment]
@DaveBeasley could you take a look at this?

**Comment by DaveBeasley** [comment]
@Jim-Parker This section builds on the previous section where you open the code component in Visual Studio or similar. A constructor creates a new instance of a pre-defined object. Something like class Person and then create a public Person constructor... I'll see if I can add some detail around the first item of opening the code component.

**Comment by Jim-Parker** [comment]
@DaveBeasley just checking to see if there's been any progress on this issue? Thanks.

**Comment by DaveBeasley** [comment]
What is this issue – where can I find this bug?

**Comment by Jim-Parker** [comment]
@DaveBeasley this is the same issue from two weeks ago. The related training module is in the users first note above.

**Comment by DaveBeasley** [comment]
thanks. The email did not tell me where this issue resided -- figured out it is a Git repo called contribute. I've made updates to this module. I'm not sure if this is what the user wanted. I will keep this in mind for future updates.

**Comment by Jim-Parker** [comment]
@georgiebrown10 I'm going to close this issue based on the actions taken. Let us know if you still have concerns. thanks.
