### ISSUE TITLE
Something is Wrong with CImage Class, Draw Function

### ISSUE THREAD

**Issue by EdwinIZ8** [MicrosoftDocs/Contribute#4]
When I want to make a image look smaller than it is, I used CImage::Draw(HDC hDestDC, int xDest, int yDest, int nDestWidth, int nDestHeight, int xSrc, int ySrc, int nSrcWidth, int nSrcHeight). But the result didn't show as it should be. Much noisy show on the image. And there is something wrong with the color.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Overview - Contributor Guide](https://docs.microsoft.com/zh-cn/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/live/Contribute/index.md)
* Service: **n.a**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by EdwinIZ8** [comment]
This is the link about CImage class below:
https://docs.microsoft.com/zh-cn/cpp/atl-mfc-shared/reference/cimage-class?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DZH-CN%26k%3Dk(ATLIMAGE%2FATL%3A%3ACImage)%3Bk(ATL%3A%3ACImage)%3Bk(CImage)%3Bk(DevLang-C%2B%2B)%3Bk(TargetOS-Windows)%26rd%3Dtrue#draw

**Comment by mikeblome** [comment]
Hi Edwin:
Resizing an image can produce noisy results if the new dimensions are not the same ratio as the old dimensions, or if the reduction in size is too great. CImage.Draw is not an intelligent image processor. You would have to write additional logic to smooth out the image, or try using DirectDraw APIs to do that work. 

If you have additional questions about DirectDraw, I suggest posting to StackOverflow.com. If you have issues with C++ documentation, please feel free to post them at this repo: https://github.com/MicrosoftDocs/cpp-docs

Mike Blome
Visual C++ Content Developer
