### ISSUE TITLE
Ambiguous reference to icon/button

### ISSUE THREAD

**Issue by Cognitive-dissonance** [MicrosoftDocs/Contribute#403]
In the section under "Quick Edit..." - #1 refers to an "pencil icon without text", and right below it, it shows a highlighted pencil icon with some text ("Edit") in it. Further down, after the next paragraph that instructs one to click the pencil icon, there is an image of a pencil icon without text. This seems to me to be slightly ambiguous, or confusing. I had a quick look, but seems I'd have to do some reading to be sure, but I'm fairly sure an employee (presumably reading this) would know.
Thanks, I hope I did everything right with all the codes and policies and all that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Jim-Parker** [comment]
@Cognitive-dissonance I've clarified the text you referenced, so I'm closing this issue. Thank you for your help.
