### ISSUE TITLE
Question on one of the examples

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/Contribute#404]
WRT to one of the examples in the percent encoding area ...

```
System.Threading.Tasks.Task``1 encodes as System.Threading.Tasks.Task%601 (see the section on generic types)
```

... there's only one backtick. Should it read ...

```
System.Threading.Tasks.Task``1 encodes as System.Threading.Tasks.Task%60%601 (see the section on generic types)
```

... or should there only be one backtick ...

```
System.Threading.Tasks.Task`1 encodes as System.Threading.Tasks.Task%601 (see the section on generic types)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcff0d60-cd99-d88d-9e21-bee20c17a4de
* Version Independent ID: ff9c4a5e-f283-9c95-b8fb-a3adb87460cc
* Content: [How to use links in documentation - Contributor Guide](https://docs.microsoft.com/en-us/contribute/how-to-write-links)
* Content Source: [Contribute/how-to-write-links.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-links.md)
* Product: **non-product-specific**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@guardrex Thanks for noticing that. I think it was authored with two backticks to try and escape it, but obviously that's the wrong way to do it.
