### ISSUE TITLE
Don't know

### ISSUE THREAD

**Issue by bdan9559** [MicrosoftDocs/Contribute#416]
www.microsoft.com
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a2aff0-d922-e8d8-8d71-31a0d393f504
* Version Independent ID: 29c0d2ea-3e0b-626b-359a-534f5192c1e0
* Content: [Install content authoring tools - Contributor Guide](https://docs.microsoft.com/en-us/contribute/get-started-setup-tools)
* Content Source: [Contribute/get-started-setup-tools.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/get-started-setup-tools.md)
* Product: **non-product-specific**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
@bdan9559 the issue description is empty. Do you need assistance? let us know if there's a question.

**Comment by Jim-Parker** [comment]
@bdan9559 I'm going to close this based on lack of actionable information. Let me know if there's a specific question you need help with.
