### ISSUE TITLE
Page has no RSS or email option for Updates

### ISSUE THREAD

**Issue by asnierma** [MicrosoftDocs/Contribute#422]
My partner shared with me they love using all of the RSS feeds for updates, roadmaps, and news.  They love this page but wanted to know if they could get it on an RSS or something like that.  Any plans to add an RSS option or email option?

Thanks,
Asher (asnierma)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
Hi @asnierma 

Do you have an example of the RSS feed from other docs pages? I haven't seen it before, and not sure which option that is.

I know the Docs search feature has an RSS subscription, for example, this wildcard search:
https://docs.microsoft.com/en-us/search/?scope=Contribute&terms=*

RSS feed of that: https://docs.microsoft.com/api/search/rss?search=*&locale=en-us&facet=&%24filter=scopes%2Fany%28t%3A+t+eq+%27Contribute%27%29

Thanks, Jason

**Comment by JasonWHowell** [comment]
There is a wishlist item here for a general docs RSS feed: https://github.com/MicrosoftDocs/feedback/issues/1116

**Comment by JasonWHowell** [comment]
We are tracking a bigger request to follow products/services/topics to get updates, but that is a long term docs platform, and it's being tracked and planned outside of the contributor guide. I'll close this issue for now, since its a long-term effort, but I have mentioned it to the right folks to plan with. 
#please-close

**Comment by asnierma** [comment]
Here is an example of partner news in an RSS feed - https://www.microsoft.com/en-us/us-partner-blog/

Thanks,
Asher


Asher Nierman
Services Account Manager
CSS Partner Enablement | Advanced Support for Partners (ASfP)<https://partner.microsoft.com/en-us/support/advanced-cloud-support>
Office: (469)-775-3272 | Asher.Nierman@microsoft.com<mailto:Asher.Nierman@microsoft.com>
ASfP Incident Support Operations is available at asfpsam@microsoft.com<mailto:asfpsam@microsoft.com>

[bannerlogo]

**Comment by JasonWHowell** [comment]
@asnierma Thanks. Yeah, that's a micorsoft.com blog platform, which has RSS. The Docs.microsoft.com documentation pages and site doesn't have RSS subscriptions at present - only the search results has RSS. Its being tracked centrall.

PS: I removed your email/ phone signature to help keep your PII off the internet. Email signatures go public when you use email reply.
