### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by nivnar** [MicrosoftDocs/Contribute#436]
> And you can see how the snippet tags are structured in [this source file](https://github.com/dotnet/samples/blob/master/snippets/csharp/language-reference/operators/ConditionalExamples.cs)

Article - https://docs.microsoft.com/en-us/contribute/dotnet/dotnet-style-guide
Broken link - https://github.com/dotnet/samples/blob/master/snippets/csharp/language-reference/operators/ConditionalExamples.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00bf1b48-5ec1-2623-e17e-73060ba79b78
* Version Independent ID: 27582428-2540-e724-96dd-e5990ef136dc
* Content: [Template and cheatsheet for .NET articles - Contributor Guide](https://docs.microsoft.com/en-us/contribute/dotnet/dotnet-style-guide)
* Content Source: [Contribute/dotnet/dotnet-style-guide.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/dotnet/dotnet-style-guide.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This was fixed in #435 which removed this section and linked to the general guidance.

@Jim-Parker Do you want to close this?

**Comment by Jim-Parker** [comment]
Yes. Thanks @BillWagner. @nivnar let me know if you have any questions and thanks for letting us know about the link.
