### ISSUE TITLE
Not clear how to select Try.NET scaffolding

### ISSUE THREAD

**Issue by pkulikov** [MicrosoftDocs/Contribute#438]
The [section about interactive code snippets](https://docs.microsoft.com/en-us/contribute/code-in-docs#code-snippets-included-by-reference) contains the following options of `interactive`:

> - `try-dotnet` - Enables Try .NET
> - `try-dotnet-class` - Enables Try .NET with class scaffolding
> - `try-dotnet-method` - Enables Try .NET with method scaffolding

However, it's not clear for which scenarios what type of scaffolding to use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d876ecc9-4bd3-7939-e085-45ee004d2ca4
* Version Independent ID: 01ce33da-da13-b0f5-a153-3e1d41d848f5
* Content: [How to include code in docs - Contributor Guide](https://docs.microsoft.com/en-us/contribute/code-in-docs#code-snippets-included-by-reference)
* Content Source: [Contribute/code-in-docs.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/code-in-docs.md)
* Product: **non-product-specific**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@BillWagner What guidance would you suggest for when to use class or method scaffolding?

**Comment by pkulikov** [comment]
@tdykstra @BillWagner more than guidance, it looks like there are some *rules*. For example, consider the interactive snippet in the following section on the .NET docs:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions#statement-lambdas

It works with `try-dotnet-method`, but doesn't work with `try-dotnet`. Why? (I haven't tried `try-dotnet-class`)

Main question: how do I know which value to provide for `interactive` in order to make the snippet actually run in the browser (and to not output compiler errors)? (I'm starting to guess by now that, most probably, for all the small snippets `try-dotnet-method` must be used.)
