### ISSUE TITLE
It would be great to have something about keeping your fork up to date

### ISSUE THREAD

**Issue by simonsabin** [MicrosoftDocs/Contribute#445]
The workflow is great at explaining the initial process. What happens when someone does their second change a month later they need to update their fork.

I believe the approach should add a step to pull from the upstream. i.e.

`
git checkout master
git pull upstream
git push
`
where master is the the branch that has the current content. I've noticed some are using live as the current published version.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c68d84b-6a64-722b-bf11-78d6e1009c4b
* Version Independent ID: 3b4e7a64-72d4-b6b0-2c23-bb2b0017becf
* Content: [GitHub contribution workflow for major or long-running changes - Contributor Guide](https://docs.microsoft.com/en-gb/contribute/how-to-write-workflows-major)
* Content Source: [Contribute/how-to-write-workflows-major.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-workflows-major.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by zatanboy** [comment]
> The workflow is great at explaining the initial process. What happens when someone does their second change a month later they need to update their fork.
> 
> I believe the approach should add a step to pull from the upstream. i.e.
> 
> `git checkout master git pull upstream git push`
> where master is the the branch that has the current content. I've noticed some are using live as the current published version.
> 
> #### Document details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 2c68d84b-6a64-722b-bf11-78d6e1009c4b
> * Version Independent ID: 3b4e7a64-72d4-b6b0-2c23-bb2b0017becf
> * Content: [GitHub contribution workflow for major or long-running changes - Contributor Guide](https://docs.microsoft.com/en-gb/contribute/how-to-write-workflows-major)
> * Content Source: [Contribute/how-to-write-workflows-major.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-workflows-major.md)
> * Product: **non-product-specific**
> * GitHub Login: @BillWagner
> * Microsoft Alias: **wiwagn**
