### ISSUE TITLE
What about items for which no Edit option exists?

### ISSUE THREAD

**Issue by SolitonMan** [MicrosoftDocs/Contribute#453]
I was reviewing the Contributing information for Microsoft Docs and read about making quick updates for items with that option available.  But I couldn't find out the process for items that don't include an Edit option.  Is there a mechanism to report errors?  I'm in the midst of a tutorial and have found a discrepancy.  If someone can help point me in the right direction I'll take the necessary steps to get it fixed.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Jim-Parker** [comment]
@SolitonMan Thanks for your feedback. In the overview article, I've clarified that absence of the edit button means that the content is not open to public contribution.
