### ISSUE TITLE
In upload data option: SDK upload, in step 2,3 there is a need to add apikeycedentials else it gives an error

### ISSUE THREAD

**Issue by soumalyatheking22012001** [MicrosoftDocs/Contribute#457]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @Jim-Parker
* Microsoft Alias: **jimpark**

**Comment by Jim-Parker** [comment]
@soumalyatheking22012001 thank you for the suggestion. Can you tell me which specific article you're referring to?

**Comment by soumalyatheking22012001** [comment]
I'm talking about this [article](https://docs.microsoft.com/en-us/learn/modules/cv-classify-bird-species/3a-upload-images).
The codes in here doesn't work it keeps giving errors. I was using python by the way.

**Comment by Jim-Parker** [comment]
@soumalyatheking22012001 I have forwarded this issue via the issue reporting functionality in that content. Waiting for a response.
thanks for letting us know about this.

**Comment by soumalyatheking22012001** [comment]
As you have reported it to the authority I'm closing this issue here. Considering I have done my part in it.
