### ISSUE TITLE
docsの日本語訳ページのフィードバックセクションで原文にある１文が表示されない。

### ISSUE THREAD

**Issue by hatsunea** [MicrosoftDocs/Contribute#46]
docsでフィードバックするときにen-USだと「Our new feedback system is built on GitHub Issues. Read about this change in our blog post.」という表記があるが、ja-jpだとその部分がない。
「本フィードバックシステムは、GitHub のissueを使っています。お寄せいただいたご意見はgithubのissueとして公開されます。」のような翻訳文での記載をすることで、日本での理解も深まると思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs 共同作成者ガイド概要 - Contributor Guide](https://docs.microsoft.com/ja-jp/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute.ja-JP/blob/live/Contribute/index.md)
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by hatsunea** [comment]
これは、特定のページというよりもdocsの日本語ページすべてに関するフォードバック＝改善点の問うことなります。

**Comment by Makopo** [comment]
I believe I have covered that in https://github.com/MicrosoftDocs/feedback/issues/554 .
@Powerhelmsman @bodhigautam @SonjaSaltzman is addressing to this issue.

**Comment by JasonWHowell** [comment]
Thanks for the feedback. Looks like the fix has been issued. Closing it out now. ~Jason
