### ISSUE TITLE
Multiple ms.authors? 

### ISSUE THREAD

**Issue by madehmer** [MicrosoftDocs/Contribute#460]
I'm curious if author and ms.author in metadata support listing more than one author for a published file? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a95b994-145b-b0df-4708-cce059b35b13
* Version Independent ID: a01dd8d6-4782-d2cd-006c-bbf9d82c2af3
* Content: [Metadata Updates - Docs Authoring Pack - Contributor Guide](https://docs.microsoft.com/en-us/contribute/docs-authoring/metadata-updates)
* Content Source: [Contribute/docs-authoring/metadata-updates.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/docs-authoring/metadata-updates.md)
* Product: **non-product-specific**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @madehmer to my knowledge, they do not.

**Comment by Jim-Parker** [comment]
Correct, one author per each of those attributes. @madehmer,  thank you for checking with us on this.
