### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by cesarsouza** [MicrosoftDocs/Contribute#465]
1. Navigate to https://docs.microsoft.com/en-us/search/
2. Enter anything in the search box (e.g., I tried searching for "string", "test", "metadata", "asp.net core")
3. Irrespective of the input terms, the page always returns:

![image](https://user-images.githubusercontent.com/528455/106731693-0edff400-6610-11eb-8dda-c2b7209451e6.png)

**Comment by Jim-Parker** [comment]
@cesarsouza can you look again? It seems to be working now.

**Comment by cesarsouza** [comment]
@Jim-Parker Thanks, I realize now that it works if I disable the Brave Shields in the Brave browser.
