### ISSUE TITLE
Search from root - docs.microsoft.com 

### ISSUE THREAD

**Issue by Zhunya** [MicrosoftDocs/Contribute#466]
The search is not working at all. Maybe not at all, but not working, from root page https://docs.microsoft.com

**Comment by Jim-Parker** [comment]
@Zhunya I'm not able to duplicate this. Are you still unable to search from https://docs.microsoft.com?

**Comment by Zhunya** [comment]
@Jim-Parker finally pinned this issue, uBlock Origin is blocking something on the page. Thank you!
