### ISSUE TITLE
docsの日本語訳ページのフィードバックセクションの「feedback」に関する日本語訳について

### ISSUE THREAD

**Issue by hatsunea** [MicrosoftDocs/Contribute#47]
en-us表記で[Prodoct Feedback]ボタンや[Content Feedback]ボタン、[Submit Feedback]ボタンについては、ja-jp表記では「製品に関する改善点」ボタンや「コンテンツに関する改善点」ボタン、[改善点を送信]ボタンという翻訳が良いと思う。
日本では「フィードバック」という表記ではなく「改善点」という表記にした方が、より前向きな意見が集まると考えます。
これは、特定のページというよりもdocsの日本語ページすべてに関するフォードバック＝改善点ということなります。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs 共同作成者ガイド概要 - Contributor Guide](https://docs.microsoft.com/ja-jp/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute.ja-JP/blob/live/Contribute/index.md)
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by aldonetti** [comment]
@SonjaSaltzman @tesheng

**Comment by SonjaSaltzman** [comment]
Adding @nokura @DavidPrio for followup

**Comment by JasonWHowell** [comment]
Was this problem already resolved in https://github.com/MicrosoftDocs/feedback/issues/571 ? or is the issue a separate problem?

**Comment by DavidPrio** [comment]
Hi @JasonWHowell Let me go over this one more time.
@CeciAc  @gosali @LisandroSu Can you please take a look at this? Thanks!

**Comment by JasonWHowell** [comment]
@DavidPrio did you hear back?

**Comment by CeciAc** [comment]
Hi team, I'm moving this to the ja-JP repo and will work on it from there since this is a Japanese linguistic issue, different from https://github.com/MicrosoftDocs/feedback/issues/571

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/Contribute.ja-JP #3](https://github.com/MicrosoftDocs/Contribute.ja-JP/issues/3) via [**ZenHub**](https://www.zenhub.com/)

**Comment by JasonWHowell** [comment]
Closing this thread, since it is handled in MicrosoftDocs/Contribute.ja-JP#3
