### ISSUE TITLE
Please Update Visual Studio 2019 version 16.8 Releases Notes

### ISSUE THREAD

**Issue by Jimmy-Hu** [MicrosoftDocs/Contribute#471]
Visual Studio 2019 Version 16.8.6 is now available. Please update [Visual Studio 2019 version 16.8 Releases Notes page](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes).

**Comment by Jim-Parker** [comment]
@Jimmy-Hu Thanks for filing this request. I'm looking for the correct person to help make the update.

**Comment by j-martens** [comment]
@Jimmy-Hu - this should be fixed now that OPS is back online. Let us know if it isn't working for you. Thank you!

**Comment by Jimmy-Hu** [comment]
@j-martens Thank you for the reply. The issue has been fixed. Happy to close :)
