### ISSUE TITLE
GitHubからdocs.microsoft.comに反映されるタイミングについて記載するべきでは。

### ISSUE THREAD

**Issue by megascus** [MicrosoftDocs/Contribute#48]
GitHub上のイシューで対応されたと連絡を受けたが、docs.microsoft.comに反映されていないため確認が出来ませんというコメントをいくつか見かけます。
いつ反映されるのかについて記載をお願いします。
https://github.com/dotnet/docs.ja-jp/issues/140#issuecomment-409057590
https://github.com/dotnet/docs.ja-jp/issues/118#issuecomment-408305243

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs 共同作成者ガイド概要 - Contributor Guide](https://docs.microsoft.com/ja-jp/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute.ja-JP/blob/live/Contribute/index.md)
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Makopo** [comment]
This issue says that the explanation about when to be published the changes to "docs.microsoft.com" is missing. I believe that it is said in the following page on this repository, which is authored by @DuncanmaMSFT:

https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/includes/contribute-how-to-write-workflows-pull-request-processing.md#publishing

> After your contributions are approved and merged, the docs.microsoft.com publishing process picks them up. Depending on the team that manages the repository you are contributing to, publishing times can vary. Articles published under the following paths are normally deployed at approximately 10:30 AM and 3:30 PM Pacific Time, Monday-Friday:

I don't know if there is immediate publishing or so though.

**Comment by megascus** [comment]
@Makopo
Thank you for the information.
I couldn’t find it.

**Comment by HACKHNATON01** [comment]
Ouh then
