### ISSUE TITLE
allow this article to download in pdf format

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/Contribute#480]
Please this article is very useful to all new users those are all want to learn markup language to edit existing article. so allow this complete article to download in pdf format..
So please consider this feedback as priority basis
 and  add download option to get in pdf format.

Thanking you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd2bb3d-3104-1be7-7232-8a194074af4b
* Version Independent ID: 2efecbe2-8538-8659-7740-6f8852f7875b
* Content: [Markdown reference for docs.microsoft.com - Contributor Guide](https://docs.microsoft.com/en-us/contribute/markdown-reference)
* Content Source: [Contribute/markdown-reference.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/markdown-reference.md)
* Product: **non-product-specific**
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by meganbradley** [comment]
@Jim-Parker @RAJU2529 

You can download the whole guide as PDF, then find the Docs Markdown reference at page 611. Unfortunately we don't have the ability to make individual pages downloaded, and PDF feature enhancements aren't a priority of this time.
