### ISSUE TITLE
Azure region does not pin at the right location on the map

### ISSUE THREAD

**Issue by lihbinn** [MicrosoftDocs/Contribute#481]
Pinned location of SouthEast Asia region on the map does not seem to be located at Singapore.
https://azure.microsoft.com/en-us/global-infrastructure/geographies/

**Comment by jehchow** [comment]
This may have changed in the past 8 months, but in reviewing the Global Infrastructure map at https://infrastructuremap.microsoft.com/, it appears that the Singapore pin is in the correct spot, and that the Southeast Asia pin is in a general location that visually represents the entire SE Asia region. Please let me know if I've misunderstood the issue, thanks.
