### ISSUE TITLE
Problem in Downloading Microsoft Certification exam - Passing Certificate

### ISSUE THREAD

**Issue by AjayKukadiya** [MicrosoftDocs/Contribute#483]
Hi There !
Good evening !!

**Problem Statement:** Problem with downloading Microsoft Exam Certificates. 

Recently I've cleared Microsoft Azure Foundation Certification exam (AZ-900), after when i download the Certificate , and try to open the microsoftcertificate.pdf file it is not opening correctly. Initially i thought it might be due to some technical reason the certificate will be available after sometime, but after checking this again later one week, still the issue remain as is. 

**Problem rootcause**
I gave multiple try in opening downloaded microsoftcertificate.pdf file with different tool. (based on my other reading) 
Then i tried (bit strage way that worked) - I renamed the downloaded "microsoftcertificate.PDF" file with microsoftcertificate.Zip and then I unzipped the content into microsoftcertificate folder. To my surprise i saw the unzip folder contained "Microsoft_Certified_Professional_Certificate_0.pdf" which then opened correctly.

So in my view , there is chance that lot of practitioner might be facing similar issue, so this issue needs to fixed by downloading the certificate with  **microsoftcertificate.Zip** file rather then microsoftcertificate.pdf. 

I have attached all my step by step to reproduce the problem scenario. 
![Step-1](https://user-images.githubusercontent.com/61040022/113723367-ead38880-970e-11eb-8c1c-1528c18646d3.JPG)
![Step-2](https://user-images.githubusercontent.com/61040022/113723376-ec04b580-970e-11eb-8996-fde6449d29c1.JPG)
![Step-3](https://user-images.githubusercontent.com/61040022/113723380-ed35e280-970e-11eb-8048-3d363e31c5a5.JPG)
![Step-4](https://user-images.githubusercontent.com/61040022/113723382-edce7900-970e-11eb-9ecb-b6a3572e8a61.JPG)
![Step-5](https://user-images.githubusercontent.com/61040022/113723385-edce7900-970e-11eb-9067-b56b3e97241b.JPG)
![Step-6](https://user-images.githubusercontent.com/61040022/113723388-ee670f80-970e-11eb-8eb1-a2a889454af8.JPG)
![Step-7](https://user-images.githubusercontent.com/61040022/113723391-eeffa600-970e-11eb-97f4-95029c8d1100.JPG)

Kindly suggest me if in case this is not the right forum, to report this with correct forum or channel.

Many thanks

**Comment by Jim-Parker** [comment]
@AjayKukadiya my apologies for the delayed response. This is not the correct forum, but I was able to find these links that should provide more help. 
•	Cert Dashboard: www.aka.ms/certdashboard
•	Certification support page on Learn: https://docs.microsoft.com/en-us/learn/certifications/help
•	Direct link to certification support forums: www.aka.ms/MCPforum 

Thank you for letting us know about this issue
