### ISSUE TITLE
Erroneous styling

### ISSUE THREAD

**Issue by Wamala-Emmanuel** [MicrosoftDocs/Contribute#521]
Content not in alignment on https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd569089(v=ws.10)

**Comment by jehchow** [comment]
Hi @Wamala-Emmanuel - I am from the Microsoft Docs contributor guide team, and I see that you opened this issue for an article for Windows Server 2008. I have raised your comment to the appropriate person within Microsoft, and they will follow up if they have any questions. Thank you for your comment!
