### ISSUE TITLE
Windows Step Recorder not well supported on Microsoft Edge

### ISSUE THREAD

**Issue by jasramek** [MicrosoftDocs/Contribute#523]
According to https://support.microsoft.com/en-us/windows/record-steps-to-reproduce-a-problem-46582a9b-620f-2e36-00c9-04e25d784e47, one can use any web browser to view step recorder script results. While this is true, in Microsoft Edge, all the image links are broken and on many blogs, they indicate the Microsoft Edge does not support MHT format, which is what step recorder results are posted to. Internet Explorer works very well, but that goes out of support in a year. What is the plan?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @Jim-Parker
* Microsoft Alias: **jimpark**

**Comment by jehchow** [comment]
Hi @jasramek - I am from the Microsoft Docs contributor guide team, and I see that you opened this issue for an article for Windows Support. I have raised your comment to the appropriate person within Microsoft, and they will follow up if they have any questions. Thank you!
