### ISSUE TITLE
Can You change the "defult" branch name from "Master" To "Main"

### ISSUE THREAD

**Issue by I-Cat** [MicrosoftDocs/Contribute#525]
TO: Previous Commiters:
@v-ashwinik
@meganbradley
@Jim-Parker
@tdykstra

Contributer: @I-Cat
Hi
Can You change the "defult" branch name from "Master" To "Main"

IS:
https://github.com/MicrosoftDocs/Contribute/tree/master
Should be:
https://github.com/MicrosoftDocs/Contribute/tree/main

Thanks

Signed-off-by:  @I-Cat

**Comment by jehchow** [comment]
Hi @I-Cat, thank you for your comment! This issue is a priority for us, and rest assured, renaming the default branch from "master" to "main" is on our roadmap. Thanks again.
