### ISSUE TITLE
Docs Authoring Pack for Visual Studio Code deprecated

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/Contribute#535]
[Its repo](https://github.com/microsoft/vscode-docs-authoring) has been archived.  If it's still supported, where should I report a technical issue?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b26339c-9a3c-de93-7806-3eb105b16ae4
* Version Independent ID: ec4aa25b-c7e2-db46-3cf1-7563e8031bd6
* Content: [Docs Authoring Pack for Visual Studio Code - Contributor Guide](https://docs.microsoft.com/en-us/contribute/how-to-write-docs-auth-pack)
* Content Source: [Contribute/how-to-write-docs-auth-pack.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-docs-auth-pack.md)
* Product: **non-product-specific**
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by carlyrevier** [comment]
@meganbradley - Can you please assist with this question from the public-facing Docs contributor guide?

**Comment by carlyrevier** [comment]
@rootsmusic - Thanks for bringing this to our attention. We're working internally to find an answer for you.

**Comment by rootsmusic** [comment]
Ok @carlyrevier, assigned?

**Comment by carlyrevier** [comment]
Unfortunately, we don't have a replacement solution for submitting feedback right now. The tool is still available for use, but we haven't identified a new place to submit feedback. Sorry for the inconvenience.

**Comment by carlyrevier** [comment]
@rootsmusic - According to the product owner, you can still [submit issues](https://github.com/microsoft/vscode-docs-authoring/issues) to the Docs Authoring Pack (now renamed Microsoft Learn Authoring Pack) repo, even though they aren't accepting public contributions to update the tool itself.

There's a PR open now to add the following sentence to the readme file to clarify this issue:

_To submit feedback on the Microsoft Learn Authoring Pack, create an issue in this repository. Please don't share sensitive or personal information. We're not accepting outside contributions, but will review issues regularly to continue improving the existing extensions._

**Comment by rootsmusic** [comment]
Thanks @carlyrevier.  Please also correct the "Repository" link (under "Resources") in the [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack&ssr=false#overview).
