### ISSUE TITLE
Version & Track Datasets in Production

### ISSUE THREAD

**Issue by pankaj1311** [MicrosoftDocs/Contribute#552]
[Enter feedback here]
Hi, Thank you for explaining this. But can you also explain how can we replicate this versioning behavior of the datasets in production?
From this code, it seems one has to keep adding new locations for the datasets to create a new version. But how does it works in production while orchestrating using Azure DevOps or Github Actions?

from azureml.core import Dataset

# get the default datastore of the workspace
datastore = workspace.get_default_datastore()

# create & register weather_ds version 1 pointing to all files in the folder of week 27
**datastore_path1 = [(datastore, 'Weather/week 27')]**
dataset1 = Dataset.File.from_files(path=datastore_path1)
dataset1.register(workspace = workspace,
                  name = 'weather_ds',
                  description = 'weather data in week 27',
                  create_new_version = True)

# create & register weather_ds version 2 pointing to all files in the folder of week 27 and 28
**datastore_path2 = [(datastore, 'Weather/week 27'), (datastore, 'Weather/week 28')]**
dataset2 = Dataset.File.from_files(path = datastore_path2)
dataset2.register(workspace = workspace,
                  name = 'weather_ds',
                  description = 'weather data in week 27, 28',
                  create_new_version = True) 

**How does the dataset version gets affected if a new parquet file is created in the same dataset location?** For eg.
# create & register sample_ds version 1 pointing to all the parquet files in the folder sample_ds
**datastore_path = [(datastore, 'sample_ds/*.parquet')]**
_# Assume currently there are 10 parquet files in this location today and 2 new files will get added tomorrow plus 2 older files will be deleted_
dataset = Dataset.File.from_files(path = datastore_path2)
dataset.register(workspace = workspace,
                  name = 'sample_ds',
                  description = 'Sample Dataset',
                  create_new_version = True) 
_# Assume the current version of sample_ds is 2 and it shall update to 3 tomorrow after 2 new files gets added and 2 older files gets deleted And if nothing gets changed in the folder then the existing version shall remain the same_
In my code, I am using the dataset.register class to register dataset for the first time but within the pipeline it also runs everytime to find out if the dataset exists with the same name if yes then it skips the registration part and proceeds with the pipeline. How does the logic be written to find out if a new version needs to be created or not for a specific dataset in production?

Now, based on a file addition or deletion from the blob location the dataset version shall also be updated. Please share some sample code or logic to maintain this behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @Jim-Parker
* Microsoft Alias: **jimpark**

**Comment by carlyrevier** [comment]
@pankaj1311 - Thanks for reaching out. You've reached our Docs contributor guide repo, rather than the writers of the article you're referencing. I can help you try to find the right people to answer this question, but I need to know which page in our documentation you were reading. Can you please provide a link to the page?

**Comment by carlyrevier** [comment]
@pankaj1311 - You have reached the Issues queue for the Docs contributor guide, not a product.

Issues submitted here are reviewed by the repo managers of the Docs contributor guide, **not product teams.** Your issue should pertain to the documentation in this [contributor guide](https://docs.microsoft.com/en-us/contribute/?branch=main) only. Requests for updates to products or product documentation will be closed.

If you have feedback about a product or product documentation, use one of these outlets instead:

- For Docs content: The feedback area at the bottom of an article. If there is none, post to our [Feedback Portal](https://feedbackportal.microsoft.com/feedback/).

- For Learn content: The feedback link at the bottom of each unit. If there is none, use the **Report feedback** tool at the very bottom of [this article](https://review.docs.microsoft.com/en-us/learn/support/troubleshooting?branch=main#report-feedback).
