### ISSUE TITLE
Word

### ISSUE THREAD

**Issue by neo361** [MicrosoftDocs/Contribute#554]
when you get error 80090016 on word 
either press continue or
go to login.windows.net
then log in
then your account will be logged in on word, if the account was a word account.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-gb/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @Jim-Parker
* Microsoft Alias: **jimpark**

**Comment by jehchow** [comment]
Closing as it has been over 30 days, and for lack of further information. Please comment and open another issue if you would like to provide us more info, thanks!
