### ISSUE TITLE
Section Build and test the web app

### ISSUE THREAD

**Issue by AJM20202021** [MicrosoftDocs/Contribute#558]
In Section Build and test the web app
We need to navigate to folder cd AccountTypesMultiOrg which is currently missing
Link - https://docs.microsoft.com/en-us/learn/modules/getting-started-identity/5-exercise-different-account-types

We get an error without going to the folder 
![image](https://user-images.githubusercontent.com/87415332/138033645-46278f76-f313-4349-a575-a545efadcaa0.png)

**Comment by 01026512732** [comment]
السلام عليكم ورحمة الله وبركاته

**Comment by carlyrevier** [comment]
@AJM20202021 - You have reached the Issues queue for the Docs contributor guide, not a product.

Issues submitted here are reviewed by the repo managers of the Docs contributor guide, **not product teams.** Your issue should pertain to the documentation in this [contributor guide](https://docs.microsoft.com/en-us/contribute/?branch=main) only. Requests for updates to products or product documentation will be closed.

If you have feedback about a product or product documentation, use one of these outlets instead:

- For Docs content: The feedback area at the bottom of an article. If there is none, post to our [Feedback Portal](https://feedbackportal.microsoft.com/feedback/).

- For Learn content: The feedback link at the bottom of each unit. If there is none, use the **Report feedback** tool at the very bottom of [this article](https://review.docs.microsoft.com/en-us/learn/support/troubleshooting?branch=main#report-feedback).
