### ISSUE TITLE
Need to update doc for https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-spell-check-api-v7-reference

### ISSUE THREAD

**Issue by evvvvvinms** [MicrosoftDocs/Contribute#583]
Hi there!
We're the owner of Bing Spell Check API, and we find the tables in current doc need update. Could you help assign the right owner to the repo? https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-spell-check-api-v7-reference

**Comment by carlyrevier** [comment]
@evvvvvinms - Hi there. You've reached the Issues queue for the customer-facing Docs contributor guide, not the documentation for the documentation you linked to. @PatrickFarley and @JasonWHowell are two MSFT authors on that documentation. Please reach out to them for help updating the documentation.

**Comment by JasonWHowell** [comment]
Hey @evvvvvinms maybe start an email with Patrick and Nitin to discuss. This isn't a space I work on anymore.  REST APIs are kind of a special reference documentation, mostly automated using Swagger specs, but some are still manually authored.

**Comment by nschonni** [comment]
Repo for all the rest API specs is https://github.com/Azure/azure-rest-api-specs

**Comment by JasonWHowell** [comment]
These are hande generated - here: https://github.com/Azure/azure-docs-rest-apis/blob/master/docs-ref-conceptual/cognitiveservices-bingsearch/bing-spell-check-api-v7-reference.md
