### ISSUE TITLE
Incorrect URL's used in Collaborative Programs

### ISSUE THREAD

**Issue by Donovand4** [MicrosoftDocs/Contribute#601]
Hi All,
It appears as if the "Program Tasks" , "Creating a new program", "Adding Documents" and "Assessment Rememdiation/Capability Program Specific Features" links is all incorrectly redirecting to the ".md" URLs which is all invalid. 

The below is an example of one of the invalid URL's with an extension of the portal where the URL's exist:
https://docs.microsoft.com/en-us/services-hub/unified/programs/program-tasks.md

![image](https://user-images.githubusercontent.com/49915971/154725112-e72f14af-640b-4aa5-85a8-e7b9bfb6fbb0.png)

Thank you

**Comment by carlyrevier** [comment]
@Donovand4 - Thanks for bringing this to our attention. You've reached the Issues queue for the contributor guide, not the Services Hub documentation. However, this was a pretty easy change to push through, so I opened a PR in the appropriate repo to address it. :)

**Comment by carlyrevier** [comment]
@Donovand4 - Yes, unfortunately, each repo can decide whether they turn on GitHub Issues feedback. We're working on improving the experience in our new [Feedback Portal](https://feedbackportal.microsoft.com/feedback/), but not all products have a space there yet.

**Comment by carlyrevier** [comment]
Closing this issue because the PR has been merged to fix the links. Thanks!
