### ISSUE TITLE
Outlook 2021 LTSC missing

### ISSUE THREAD

**Issue by blushta** [MicrosoftDocs/Contribute#602]
Dear Technet,

I noticed that under Outlook section, Outlook 2021 LTSC is missing.

Can you please update the article and include Outlook 2021 LTSC in the compatibility matrix?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @Jim-Parker
* Microsoft Alias: **jimpark**

**Comment by carlyrevier** [comment]
@blushta - Hi there. Issues submitted here are reviewed by the repo managers of the Docs contributor guide, **not product teams or TechNet.** Your issue should pertain to the documentation in this [contributor guide](https://docs.microsoft.com/en-us/contribute/?branch=main) only. Requests for updates to products or product documentation will be closed.

If you have feedback about a product or product documentation, use one of these outlets instead:

- For Docs content: The feedback area at the bottom of an article. If there is none, post to our [Feedback Portal](https://feedbackportal.microsoft.com/feedback/).

- For Learn content: The feedback link at the bottom of each unit. If there is none, use the **Report feedback** tool at the very bottom of [this article](https://review.docs.microsoft.com/en-us/learn/support/troubleshooting?branch=main#report-feedback).

Thank you!
