### ISSUE TITLE
Question About New Documentation Sets

### ISSUE THREAD

**Issue by NicomacheanEudaimonia** [MicrosoftDocs/Contribute#626]
Hi! Thanks for the helpful contributor guidelines. I had a few quick questions about the following:

1. What is the best place to request the creation of a new documentation set (please forgive my lack of familiarity with the current process/procedures)? Is that required?
2. Must the above be requested / submitted for customized documentation projects?
3. How much customization can we request (or is possible)? What if our documentation needs require customer-facing authentication or non-public access? Is there a required or formal process for that?

Thanks so much! My sincere apologies if this is addressed somewhere - spent some time trying to track that down and would like to get some clarity around the above as we lay our initial documentation plans.

(If this PR is not the best way to reply, please feel free to do so in Teams!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by jehchow** [comment]
@NicomacheanEudaimonia Are you internal or external to Microsoft? It's unclear from your questions and profile which you are - you've reached us through the external contributor guide. If you are internal, please reach out to me via internal channels, and we can assist you. Thanks!

**Comment by NicomacheanEudaimonia** [comment]
Hi @jehchow - sent a private message. Thanks!
