### ISSUE TITLE
Please add how to re-open a PR after auto-closer closes it

### ISSUE THREAD

**Issue by mattmccleary** [MicrosoftDocs/Contribute#630]
The auto-closer came by and closed my PR. I want to reopen it. I've tried #please-open and a bunch of other stuff and nothing seems to work. Our Azure Monitor docs team is baffled too. Can you help? Here's an example PR.
https://github.com/MicrosoftDocs/azure-docs-pr/pull/178091

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c68d84b-6a64-722b-bf11-78d6e1009c4b
* Version Independent ID: 3b4e7a64-72d4-b6b0-2c23-bb2b0017becf
* Content: [GitHub contribution workflow for major or long-running changes - Contributor Guide](https://docs.microsoft.com/en-us/contribute/how-to-write-workflows-major)
* Content Source: [Contribute/how-to-write-workflows-major.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/how-to-write-workflows-major.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by jehchow** [comment]
Hi @mattmccleary - You've reached us at our external-facing contributor guide. I'll reach out to you internally to point you to the article that you're looking for. Thanks!
