### ISSUE TITLE
Question on the NOTE about build source folder and cross-repo snippet links

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/Contribute#631]
Hi Tom ...

The NOTE in the *Out-of-repo snippet references* section states ...

> The name you assign to the dependent repository is relative to the root of the main repository, but the tilde (`~`) refers to the root of the doc set. The doc set root is determined by `build_source_folder` in `.openpublishing.publish.config.json`. The path to the snippet in the preceding example works in the azure-docs repo because `build_source_folder` refers to the repo root (`.`). If `build_source_folder` were `articles`, the path would start with `~/../samples-durable-functions` instead of `~/samples-durable-functions`.

What is the parent path segment replacing or covering when the `build_source_folder` isn't the repo root (`.`)? It's not "`articles`" for a `build_source_folder` of `articles` because the following breaks 💥 ...

```markdown
:::code ... source="~/articles/samples-durable-functions/samples/csx/shared/Location.csx" ...:::
```

... so what is it covering in the path if not "`articles`"? Why can't it be replaced with an explicit segment?

If this is more of a DocFX ❓ than something that you'd like to address in a doc update to the NOTE to clarify it further, then please go ahead and close this issue ... I'll ask via an internal DocFX issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d876ecc9-4bd3-7939-e085-45ee004d2ca4
* Version Independent ID: 01ce33da-da13-b0f5-a153-3e1d41d848f5
* Content: [How to include code in docs - Contributor Guide](https://docs.microsoft.com/en-us/contribute/code-in-docs#out-of-repo-snippet-references)
* Content Source: [Contribute/code-in-docs.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/code-in-docs.md)
* Product: **non-product-specific**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
> for a `build_source_folder` of `articles` because the following breaks 💥 ...
> 
> ```gfm
> :::code ... source="~/articles/samples-durable-functions/samples/csx/shared/Location.csx" ...:::
> ```

for a `build_source_folder` of `articles` I would expect you to need to go up one level as in the example in the note, by starting the path with tilde (`~`) to get to `articles` and then dot-dot (`/..`) to get to the repo root one level up. Once you're at the repo root, you can use the name you gave to the dependent repository.
