### ISSUE TITLE
"Learn about Silver and Gold competency membership levels" link server error

### ISSUE THREAD

**Issue by Gerasz87** [MicrosoftDocs/Contribute#640]
Hello,

I've found a server error page and there was no feedback section at the bottom of the page.

the page where the problematic link is located and the feedback is missing:
https://docs.microsoft.com/en-us/partner-center/mpn-get-action-pack 

The problematic link on that page:
[Learn about Silver and Gold competency membership levels](https://partner.microsoft.com/membership/internal-use-software#simple-tab-content-2)

The server error:

![2022-06-30 14_08_52-server error](https://user-images.githubusercontent.com/40123577/176674822-b5e2ffa7-13d7-4bc2-ac0b-552338536891.png)

**Comment by jasongroce** [comment]
Thanks for the feedback, @Gerasz87 ! We've updated the link to point to the correct location. #please-close

**Comment by Gerasz87** [comment]
Thanks for the quick fix!
