### ISSUE TITLE
The first sentence in this page doesn't make sense

### ISSUE THREAD

**Issue by jason934** [MicrosoftDocs/Contribute#665]
This sentence doesn't make sense, "Azure Log Analytics is a service within Azure and our On-Demand Assessment are hosted in Azure Log Analytics thus An Azure subscription is needed to use Azure Log Analytics. "

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://learn.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by jehchow** [comment]
@jason934 Hello there. Issues submitted here are reviewed by the repo managers of the Docs contributor guide, not product teams, such as Azure Log Analytics. Your issue should pertain to the documentation in this [contributor guide](https://docs.microsoft.com/en-us/contribute/?branch=main) only. 

If you have feedback about a product or product documentation, use the feedback feature on that page, typically represented by a thumbs up/down icon that you can select. After you've selected thumbs up or down, you can type in any feedback you have on that page. Thank you!
