### ISSUE TITLE
Error in a "Learn" page

### ISSUE THREAD

**Issue by dcromley** [MicrosoftDocs/Contribute#672]
Sorry if this is not the place for this.
In page https://learn.microsoft.com/en-us/office/vba/language/reference/user-interface-help/collection-object
the phrase 
  "Class1 (type Public InstanceName)"
I'm quite sure should be 
  "Class1 (Public InstanceName type) "
Best to you all.

**Comment by jehchow** [comment]
@dcromley Hello there. Issues submitted here are reviewed by the repo managers of the Microsoft Learn [contributor guide](https://docs.microsoft.com/en-us/contribute/?branch=main), not product teams. Your issue should pertain to the documentation in this contributor guide only.

If you have feedback about a product or product documentation, use the feedback feature on that page, typically represented by a thumbs up/down icon that you can select. After you've selected thumbs up or down, you can type in any feedback you have on that page. Thank you!
