### ISSUE TITLE
Mistake in [MS-WUSP] 2.1.1.1.2 DIRECT2 encoding algorithm

### ISSUE THREAD

**Issue by JiafengLiao** [MicrosoftDocs/Contribute#680]
[Enter feedback here]
Hi,

Thanks for providing the document. There is a mistake in "Bitmask". "For example, given a hypothetical 8-bit bitmask, the string "ABCABCDEF" is  compressed as (0,0)A(0,0)B(0,0)C(3,3)D(0,0)E(0,0)F."
Based on the algorithm description, the correct form after compression "ABCABCDEF" should be "(0,0)A(0,0)B(0,0)C(3,3)(0,0)D(0,0)E(0,0)F".

Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Learn documentation contributor guide overview - Contributor guide](https://learn.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by jehchow** [comment]
@JiafengLiao - Hi there. Issues submitted here are reviewed by the repo managers of the Docs contributor guide, not product teams. Your issue should pertain to the documentation in this [contributor guide](https://docs.microsoft.com/en-us/contribute/?branch=main) only. Requests for updates to products or product documentation will be closed.

If you have feedback about a product or product documentation, use one of these outlets instead:

For Documentation content: The feedback button at the top right of an article. If there is none, post to our [Feedback Portal](https://feedbackportal.microsoft.com/feedback/).

For Training content: The **reporting an issue ** link at the bottom of each unit. If there is none, use the Report feedback tool at the very bottom of [this article](https://learn.microsoft.com/en-us/training/support/troubleshooting#report-feedback).

Thank you!
