### ISSUE TITLE
Suggestion to reference specific error message wording

### ISSUE THREAD

**Issue by martillodecampo** [MicrosoftDocs/Contribute#691]
[Enter feedback here]
I made the registry changes suggested in the article at https://learn.microsoft.com/en-us/office/troubleshoot/onenote/error-sync-notebook and this fixed a sync error that I started experiencing with OneNote 365 when trying to sync notebooks located in SharePoint. The problem seemed to surface after Windows updates that were applied on Dec 13 2022. What I'd like to point out is that I never saw the error codes mentioned in the article. Instead, the error messages I saw stated that OneNote couldn't sync the notebook because I didn't have/no longer had permission to it and that I should contact the notebook owner. Unfortunately, I didn't take screenshots of most of the error messages so I can't give you their specific wording. Here's one that I did copy verbatim which occurred after I had closed an notebook and then tried to re-open it: "We couldn't open that location. It might not exist or you might not have permission to open it." I'm a Global Administrator in our Active Directory and the owner of the SharePoint sites where the notebooks were located, so the error messages didn't make any sense. If the article referenced these error messages then it would be easier for users experiencing this problem to find the article via a search on the web.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Learn documentation contributor guide overview - Contributor guide](https://learn.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by jehchow** [comment]
@martillodecampo Hello there. Issues submitted here are reviewed by the repo managers of the Microsoft Learn [contributor guide](https://learn.microsoft.com/en-us/contribute/), not product teams. Your issue should pertain to the documentation in this contributor guide only.

If you have feedback about a product or product documentation, use the feedback feature on that page, typically represented by a feedback link with a thumbs up icon. After you've selected the feedback link on the page, you can type in any feedback you have and submit it. Thank you!
