### ISSUE TITLE
ربط مستند من تعليم مايكروسفت __ربط مشكلة جيثب

### ISSUE THREAD

**Issue by alaaaldeenissam** [MicrosoftDocs/Contribute#695]
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ learn.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Learn documentation contributor guide overview - Contributor guide](https://learn.microsoft.com/ar-sa/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by jehchow** [comment]
@alaaaldeenissam I'd like to understand this issue - would you be able to write it in English, as we author the guide in English? Thank you!

**Comment by jehchow** [comment]
Closing due to no response - please comment if you have additional follow-up feedback, or open a new issue. Thank you!
