### ISSUE TITLE
https://xref.learn.microsoft.com links not working for me

### ISSUE THREAD

**Issue by v-jbasden** [MicrosoftDocs/Contribute#719]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

The https://xref.learn.microsoft.com links to the autocomplete site are not working for me (they return "This site can't be reached" error message). 

Are these links supposed to start with "https://xref.docs.microsoft.com..." instead?

For example, if I change: 

- https://xref.learn.microsoft.com/query?uid=System.String

to

- https://xref.docs.microsoft.com/query?uid=System.String

the latter "docs" link fetches data.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fcff0d60-cd99-d88d-9e21-bee20c17a4de
* Version Independent ID: ff9c4a5e-f283-9c95-b8fb-a3adb87460cc
* Content: [How to use links in documentation - Contributor guide](https://review.learn.microsoft.com/en-us/contribute/how-to-write-links?branch=main)
* Content Source: [Contribute/how-to-write-links.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/how-to-write-links.md)
* Product: **non-product-specific**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Good catch @v-jbasden. I guess these URLs were mistakenly updated as part of a bulk update.
