### ISSUE TITLE
Renewal assessment for Microsoft Certified: Azure Developer Associate typo

### ISSUE THREAD

**Issue by sandole** [MicrosoftDocs/Contribute#723]
On one of the questions for Renewal assessment for Microsoft Certified: Azure Developer Associate, the question starts like this:

```You plan to to provision the following resource in Azure App Configuration:```

There are two to's that should be corrected.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Learn documentation contributor guide overview - Contributor guide](https://learn.microsoft.com/en-ca/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by jehchow** [comment]
@sandole Hello there. Issues submitted here are reviewed by the repo managers of the Microsoft Learn [contributor guide](https://learn.microsoft.com/en-us/contribute/), not product teams. Your issue should pertain to the documentation in this contributor guide only.

If you have feedback about a product training or product documentation, use the feedback feature on that page, typically represented by the star rating at the bottom of the page under **How are we doing?** After you've provided a rating, you can type in any feedback you have on that page. Thank you!
