### ISSUE TITLE
Learn page doesn't allow sign in on Safari

### ISSUE THREAD

**Issue by elmckinn** [MicrosoftDocs/Contribute#729]
I can sign in on the main Microsoft page, but as soon as I go to Learn or any of the subpages I'm not signed in anymore and clicking "sign in" doesn't do anything. I was able to sign in from Chrome.

**Comment by jehchow** [comment]
@elmckinn Thanks for letting us know. There was a known issue that was affecting several different devices and browsers, and it appears to have been resolved. Can you check to see if it has been resolved for you?

**Comment by jehchow** [comment]
Closing, as this issue appears to have been resolved from our end. Please open a new issue if this issue persists for you, thanks!
