### ISSUE TITLE
ERROR_COULD_NOT_CONNECT_TO_REMOTESVC is often caused by rate limiting

### ISSUE THREAD

**Issue by WishesAreFishes** [MicrosoftDocs/Contribute#733]
[Enter feedback here]
When using a free Azure account, you will likely see this error message when your process is exhausting your bandwidth. One example of this is the use of a CD pipeline with parallel branches. You can address this particular issue by making your pipeline serial/sequential instead of parallel. Other users have spent literally days fighting this issue, so be glad that we include this helpful content because of their pain. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Learn documentation contributor guide overview - Contributor guide](https://learn.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by jehchow** [comment]
@WishesAreFishes Hello, issues submitted here are reviewed by the repo managers of the Microsoft Learn [contributor guide](https://learn.microsoft.com/en-us/contribute/), not product teams. Your issue should pertain to the documentation in this contributor guide only.

If you have feedback about a product or product documentation, use the feedback feature on that page, typically represented by a feedback link with a thumbs up icon. After you've selected the feedback link on the page, you can type in any feedback you have and submit it. 

For feedback about a product training, use the feedback feature on that page, typically represented by the star rating at the bottom of the page under **How are we doing?** After you've provided a rating, you can type in any feedback you have on that page. Thank you!

**Comment by WishesAreFishes** [comment]
OK. Just to be clear, I have submitted a viable request to update
documentation on your site. I followed the on-page prompts to do so.

Now, as a competent and professional Microsoft employee, it is your job to
TEACH ME how to inform you that your documentation is DEFICIENT and that
you should fix it. And what you intend to teach me is to IGNORE the
on-screen prompts on the page in question. Furthermore, this is presumably
what you TEACH anyone else STUPID ENOUGH to follow the on-screen prompts.

I count four Microsoft defects that need to get fixed here, in addition to
the original defect that I TOOK MY PRECIOUS TIME TO REPORT:
1) The on-screen prompts are either incorrect, unclear or imprecise. FIX
THAT
2) The person responsible for handling traffic thus improperly directed
TEACHES PEOPLE HOW TO GET AROUND THE SYSTEM. FIX THIS
3) The person responsible for handling said traffic is not charged with
properly routing the data thus disclosed. FIX THIS
4) Any employee within Microsoft has infinitely more information on
properly routing such requests than some shmo who is likely to make
precisely ONE such contribution and should take ownership of the issue
rather that SHOVE IT BACK TO THE ONE WHO SURFACED THE ISSUE as if that POOR
FOOL needs to be educated in how to submit change requests to Microsoft.
FIX THIS

Finally, of course, please fix your otherwise useful (I suppose)
documentation, as I suggested.


Sincerely,

Tom Huguenard
