### ISSUE TITLE
From Server to SharePoint Help!!

### ISSUE THREAD

**Issue by SeanG1992** [MicrosoftDocs/Contribute#736]
Office 365 has not been used at my work to it's fullest capabilities. Things have started, but I'm trying to advance this process. Here is the issue I am having. 

We've always stored our files on the server. 
I now want to store them in SharePoint. Most of our files were transferred to teams and SharePoint once already as more of a test. We have enjoyed working coherently and I want to make it permanent.

Problem is, some of us were working on files and folders from the server and others were working on the same files and folders from office 365. 

I need to be able to upload folders from the server to SharePoint without duplicating everything. I don't want to save over all files as originals as some files are more up to date in office365. 

What is the most effective way to tranfer the large group of folders from the server, to SharePoint, without deleting or overwiting the files more up to date in office365?

** Keep in mind, the two large groups of folders are probably close to 90% the same. It is far too many files to pick through each project folder to see what is missing or which has a more recent edit date, then only transfer those to SharePoint.

I'd like to streamline this process. Any ideas?

Thanks!

**Comment by carlyrevier** [comment]
Hello, @SeanG1992 - Issues submitted here are reviewed by the repo managers of the Microsoft Learn [contributor guide](https://learn.microsoft.com/contribute/), not product teams. Your issue should pertain to the documentation in this contributor guide only; for that reason, I'm going to close this issue.

Have you checked out our Q&A community on Microsoft Learn? There's a community [specific to SharePoint](https://learn.microsoft.com/en-us/answers/tags/235/office-sp) where you can post questions like this and search questions that others have asked. I recommend taking this question to Q&A and seeing what kind of help you can get!
