### ISSUE TITLE
Image size too big 

### ISSUE THREAD

**Issue by Sherd21** [MicrosoftDocs/Contribute#741]
Hi!
The gif on this page, used to illustrate image compression, is 26Mb. I think it maybe too big. 
The same true for other pictures in Contribute guide - simple screenshot can be >5Mb.
I would recommend to compress images where possible.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6333b614-4f09-a7ec-e964-44daf182f1d3
* Version Independent ID: 5cce4e15-a13d-8bdd-3688-23ad37236423
* Content: [Image Compression - Learn Authoring Pack - Contributor guide](https://learn.microsoft.com/en-us/contribute/docs-authoring/image-compression)
* Content Source: [Contribute/docs-authoring/image-compression.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/docs-authoring/image-compression.md)
* Product: **non-product-specific**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by jehchow** [comment]
@Sherd21 Thanks for the suggestion! We'll definitely take a pass through all of the images that are currently being used in this guide and update accordingly. Putting this on our internal workboard. 👍
