### ISSUE TITLE
How much time will it take to reflect the changes on the corresponding article page

### ISSUE THREAD

**Issue by ankur021188** [MicrosoftDocs/Contribute#758]
[Enter feedback here]
After the PR has been reviewed and merged, how much time will it take to reflect the changes on the corresponding article page?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Learn documentation contributor guide overview - Contributor guide](https://learn.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by jehchow** [comment]
@ankur021188 Thank you for inquiring! Once the PR has been reviewed and merged, it will still take some time to actually publish the merged PR. As described in the [Full workflow article > Publishing section](https://learn.microsoft.com/en-us/contribute/how-to-write-workflows-major#publishing):

_Depending on the team that manages the repository you are contributing to, publishing times can vary. Articles published under the following locations are normally deployed at approximately 10:30 AM and 3:30 PM Pacific Time, Monday-Friday:

- [Azure documentation](https://learn.microsoft.com/en-us/azure/)
- [ASP.NET documentation](https://learn.microsoft.com/en-us/aspnet/)
- [.NET documentation](https://learn.microsoft.com/en-us/dotnet/)
- [Enterprise Mobility + Security documentation](https://learn.microsoft.com/en-us/enterprise-mobility-security)

It can take up to 45 minutes for articles to appear online after publishing. After your article is published, you can verify your changes at the appropriate URL: https://learn.microsoft.com/<path-to-your-article-without-the-md-extension>._

Hope that helps!
