### ISSUE TITLE
Documentation for special quotes

### ISSUE THREAD

**Issue by dend** [MicrosoftDocs/Contribute#76]
Today, the [Markdown guide](https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown) contains a lot of useful information, but does not cover how to use special quotes.

Specifically:

```markdown
>[!IMPORTANT]
>Content here.
```

```markdown
>[!NOTE]
>Content here.
```

```markdown
>[!TIP]
>Content here.
```

```markdown
>[!CAUTION]
>Content here.
```

```markdown
>[!WARNING]
>Content here.
```

**Comment by dend** [comment]
cc: @BillWagner

**Comment by riverar** [comment]
Please also add information that answers the questions:
* Is the note block name case-sensitive? (`!WARNING`, `!Warning`, etc.)
* Is the note block tag meant to be on a line by itself? (e.g. Is `[!CAUTION] Bacon ahead` okay?)
* Is the block-quote required? What about the space after the `>`? (e.g `>[!WARNING]`, `> [!WARNING]`
* Are note blocks supported in tables?

I see varying implementations all over the docset so having an authoritative page helps guide my edits, thanks!

**Comment by riverar** [comment]
It would also be helpful if we had some guidance on what to do when we see this: https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantServicePrincipalPermissionRequests.md

Seems like a valid implementation of the note block but it's not rendering correctly https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenantserviceprincipalpermissionrequests?view=sharepoint-ps

**Comment by sptramer** [comment]
The AzPS repo is definitely set up for this. If it's the generic PowerShell / PowerShell Core repo that has some issues, check with @sdwheeler .
