### ISSUE TITLE
What impact does ms.date have and should we ever update it?

### ISSUE THREAD

**Issue by johnstep** [MicrosoftDocs/Contribute#760]
The documentation states for `ms.date`:

https://learn.microsoft.com/contribute/metadata
> Displayed on the published page to indicate the last time the article was substantially edited or guaranteed fresh. The date is entered without time and is interpreted as 0:00 and in the UTC time zone. The date displayed to users is converted to their time zone.

However, I noticed this is rarely updated (if ever, for most pages) and is generally _not_ the date displayed on the page. The date shown on the page is often, but not always, the date of the last commit to the page. Should we ever update `ms.date`?

**Comment by jehchow** [comment]
@johnstep From our understanding, that definition is still generally accurate for the `ms.date` value. The `ms.date` value _should_ be reflected as the date that is displayed at the top of the page. As noted in that definition, `ms.date` values should be updated whenever the content has been substantially changed, or reviewed and verified to be fresh. Thanks for checking!

**Comment by johnstep** [comment]
@jehchow Thank you. Unfortunately, this is not what we are seeing. The date shown on the page does not reflect the `ms.date` value. For example, we updated `ms.date` to 03/30/2023 here, but the page shows 03/08/2023:

https://learn.microsoft.com/sysinternals
> Article - 03/08/2023 - 2 minutes to read

We left `ms.date` unchanged on other pages, and the date matches neither `.ms.date` nor the last commit date.
