### ISSUE TITLE
[Alert Are Not Working!!!!!]

### ISSUE THREAD

**Issue by MrMoshkovitz** [MicrosoftDocs/Contribute#765]
[Alert Are Not Working!!!!!]
![image](https://user-images.githubusercontent.com/50079480/230899773-835692b0-0e2c-4ccc-b2a2-965a041f3cad.png)
![image](https://user-images.githubusercontent.com/50079480/230899805-549da540-89bf-4878-9e44-0d97d7b19b42.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd2bb3d-3104-1be7-7232-8a194074af4b
* Version Independent ID: 2efecbe2-8538-8659-7740-6f8852f7875b
* Content: [Markdown reference for Microsoft Learn - Contributor guide](https://learn.microsoft.com/en-us/contribute/markdown-reference)
* Content Source: [Contribute/markdown-reference.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/markdown-reference.md)
* Product: **non-product-specific**
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by carlyrevier** [comment]
Hi @MrMoshkovitz - Thank you for submitting this issue! I double-checked the Markdown page, and the alerts are working for me. Are you able to see them properly now when you view the page? 

![image](https://user-images.githubusercontent.com/23123030/231016473-50cea2aa-82e0-4d55-9c0d-5ffbfab74c14.png)

**Comment by carlyrevier** [comment]
Closing this issue because alerts are working and we haven't heard back from the poster.

**Comment by nschonni** [comment]
Doesn't need to be reopened, but I think the author's confusion was expecting the Docs format to render correctly on GitHub. That doesn't work since they're not part of the GitHub Flavored Mardkown, but custom extensions used for docs.microsoft.com
