### ISSUE TITLE
Unexpected results from following instructions: ~10,000 YAML files!

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/Contribute#767]
Hello. I've been following the instructions of the Contributor Guide. I accomplished everything said in the following pages:

1. "[Install content authoring tools](https://learn.microsoft.com/en-us/contribute/get-started-setup-tools)"
2. "[Set up Git repository locally for documentation](https://learn.microsoft.com/en-us/contribute/get-started-setup-local)"

In other words, I cloned `MicrosoftDocs/windows-powershell-docs`, opened Visual Studio Code, installed the Authoring Pack, and I'm about to contribute. But something is wrong. **I have ~10K pending changes!** All of them are new YAML files. 25 years of experience in the IT industry tells me this isn't normal. The process that created these new 10K files is called `docfx.exe` and is a component of the Authoring Pack.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3a2aff0-d922-e8d8-8d71-31a0d393f504
* Version Independent ID: 29c0d2ea-3e0b-626b-359a-534f5192c1e0
* Content: [Install content authoring tools - Contributor guide](https://learn.microsoft.com/en-us/contribute/get-started-setup-tools)
* Content Source: [Contribute/get-started-setup-tools.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/get-started-setup-tools.md)
* Product: **non-product-specific**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by carlyrevier** [comment]
@skycommand - Thanks for submitting this issue and for contributing to our documentation! I'm not sure why you're seeing all those changes, but I've posted this question to our greater docs support channel to try to figure it out. Hopefully I'll have an answer for you soon!

**Comment by JasonWHowell** [comment]
What's the nature of the changes? VSCode should show a diff.

**Comment by skycommand** [comment]
@JasonWHowell The nature of the change is that `docfx.exe` adds 15,514 `.yml` files and changes 13 others. Here is a screenshot:

![Screenshot](https://user-images.githubusercontent.com/17097175/233518130-50e0c990-be86-420f-90f3-87c7f477bdd0.png)

**Comment by JasonWHowell** [comment]
I'm not familiar with that repo. Maybe the the repo contributors are more familiar with the build process. I think it was MTrilbeyBasset and some others who know that PowerShell subject well (from perusing recent pull requests there). It could either be that the docset was built locally (something docfx would do), or a pull (fetch+commit) didn't get committed due to an error. I think there is an output view in the tabs at the bottom that might show some history, but the screen looks empty in the screenshot.

**Comment by skycommand** [comment]
I'm afraid I have no idea what you mean because I'm not familiar with Microsoft's internal workings. From my point of view, the tooling, repositories, and instructions come from one entity known as "Microsoft Corporation." All I could do was decide where to report this problem.

If you have tangible advice as to how I must proceed with my PR, I'm all ears.

**Comment by JasonWHowell** [comment]
@skycommand What are you trying to accomplish?  You can do most light edits in the browser without needing to use the full clone + VS code.

**Comment by JasonWHowell** [comment]
My guess is the clone was interrupted or a pull from the origin main branch was incomplete or something like that. I cloned the same repo freshly and opened it in VSCode without this problem.

**Comment by skycommand** [comment]
@JasonWHowell I can now confirm that there is no cloning issue. A user on Reddit helped me fix the problem. He recommended:

> Do either:
> - Install a per-user or portable copy of VSCode and do your thing there
> - Run VSCode with admin privileges

I'm not going to run VSCode with admin privileges, so I went with the portable copy. It worked.
