### ISSUE TITLE
Broken link to cla.dotnetfoundation.org

### ISSUE THREAD

**Issue by blake-fm** [MicrosoftDocs/Contribute#776]
cla.dotnetfoundation.org does not resolve.  Confirmed on a few unrelated DNS servers.

https://cla.azurewebsites.net/ works fine (DNS history says above domain was CNAME'd there).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d80fc813-0f5a-a286-fc1c-c792c96c15b9
* Version Independent ID: cd89f9f6-c81b-e64e-49fb-54cf639eef37
* Content: [Contribute to the .NET documentation repositories - Contributor guide](https://learn.microsoft.com/en-us/contribute/dotnet/dotnet-contribute)
* Content Source: [Contribute/dotnet/dotnet-contribute.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/dotnet/dotnet-contribute.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by carlyrevier** [comment]
@BillWagner - Can you help with this issue?

**Comment by blake-fm** [comment]
FYI, the .NET Foundation folks are tracking this at: https://github.com/dotnet-foundation/wg-maintainers/issues/91

**Comment by jehchow** [comment]
This issue is now resolved and the original URL is functioning. Thanks!
