### ISSUE TITLE
Safety Admonitions

### ISSUE THREAD

**Issue by RODpractise** [MicrosoftDocs/Contribute#778]
Danger, Warning, Caution, Are best used ONLY in the case of a hazard  involving  death or Injury as described in  ANSI Z535.6 and ISO 3864 standards and  when the hazard can only lead to property damage but no personal injury or death, the safety alert symbol shall never be used .

For years these standards have been ignored by software documentation as not relevant. The importance of uniform standards for safety information is, in reality, very high especially in a technology convergent world. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd2bb3d-3104-1be7-7232-8a194074af4b
* Version Independent ID: 2efecbe2-8538-8659-7740-6f8852f7875b
* Content: [Markdown reference for Microsoft Learn - Contributor guide](https://learn.microsoft.com/en-us/contribute/markdown-reference#alerts-note-tip-important-caution-warning)
* Content Source: [Contribute/markdown-reference.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/markdown-reference.md)
* Product: **non-product-specific**
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by carlyrevier** [comment]
Thank you for this feedback and awareness. I've passed this comment on to our Editorial Standards & Guidance team for consideration.
