### ISSUE TITLE
Auto Light/Dark/HC theme.

### ISSUE THREAD

**Issue by rokejulianlockhart** [MicrosoftDocs/Contribute#791]
*Because https://github.com/MicrosoftDocs/Contribute/issues/174#issue-395353473 was asked at https://github.com/MicrosoftDocs/Contribute/issues and not transferred, I'll consider https://github.com/MicrosoftDocs/Contribute to be a kind of stand-in for an organization-wide (GitLab-like) issue tracker.*

I'd like to suggest that the Microsoft Docs website itself rather than any specific documentation conform to the OS-wide system colouration preference. Currently, the user can choose Light or Dark manually, but there's no need for this – why not have the website decide which to use based upon the exposed standard browser API?

![image](https://github.com/MicrosoftDocs/Contribute/assets/42837531/c1315a2b-139e-48a7-97a2-8ba64c2eda3a)

If the browser is also able to automatically determine whether a Windows user is using a High Contrast theme, accessibility would also be positively impacted, since the user wouldn't have to manually choose that theme upon first visit.

**Comment by jehchow** [comment]
@rokejulianlockhart Thanks for your feedback! I'm passing it onto the appropriate internal team for their consideration. For any feedback in the future for Microsoft Learn, please visit: https://learn.microsoft.com/training/support/troubleshooting. At the bottom of the page, there's a way to submit feedback directly about the Learn experience, where it will reach the appropriate team.

**Comment by rokejulianlockhart** [comment]
> At the bottom of the page, there's a way to submit feedback directly about the Learn experience, where it will reach the appropriate team.

However, @jehchow, can I track the progress of such requests? If they're just sent into the ether instead of somewhere like https://feedbackportal.microsoft.com/feedback, I'll end up filing loads of duplicate requests or never knowing whether they've actually reached someone.

Thanks anyway.
