### ISSUE TITLE
Add GraphQL syntax highlighting

### ISSUE THREAD

**Issue by seantleonard** [MicrosoftDocs/Contribute#793]
Would like to see support for GraphQL syntax highlighting.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d876ecc9-4bd3-7939-e085-45ee004d2ca4
* Version Independent ID: 01ce33da-da13-b0f5-a153-3e1d41d848f5
* Content: [How to include code in docs - Contributor guide](https://learn.microsoft.com/en-us/contribute/code-in-docs#inline-code-blocks)
* Content Source: [Contribute/code-in-docs.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/code-in-docs.md)
* Product: **non-product-specific**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
We do have support for GraphQL, it was just left out of the list in this article. I'm adding it in Pull Request #794

**Comment by seantleonard** [comment]
Awesome, thank you!
