### ISSUE TITLE
PRs and issues in milestone

### ISSUE THREAD

**Issue by armizl** [MicrosoftDocs/Contribute#795]
The page says milestones should only contain PRs, but the example milestone for July 2023 contains issues. So, what is the actual guideline?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa93f96f-676a-e04b-bf4e-8185e1e8ac48
* Version Independent ID: 7d556a33-befd-e8cd-9bfd-68fc8d49493d
* Content: [Labels, projects, and milestones roadmap - Contributor guide](https://learn.microsoft.com/en-us/contribute/dotnet/labels-projects)
* Content Source: [Contribute/dotnet/labels-projects.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/dotnet/labels-projects.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by carlyrevier** [comment]
@BillWagner @tdykstra - Can you help with this issue?

**Comment by tdykstra** [comment]
The guide is correct, the issues in the July milestone were added to it by mistake and will be removed.

**Comment by carlyrevier** [comment]
Closing this issue as there is no action to take.
