### ISSUE TITLE
Contributor/index.html: GitHub does not display an edit-icon at Quick-edit step 2.

### ISSUE THREAD

**Issue by orcmid** [MicrosoftDocs/Contribute#801]
The current GitHub response does not align with `edit-article.png`.

![F23xy072-2023-07-30-1232-NoSecondEditButton](https://github.com/MicrosoftDocs/Contribute/assets/3372580/9b439fba-119f-4ced-b5b1-b1e54b663c18)

There is no tooltip on the matter. 

There is nothing that indicates there must be a sign-in or sign-up apart from the top strip of the page, if that is noticed and considered.   If a visitor mouses over some of the repository menu bar items (e.g., `Issues`), the need for a Github account/signin is indicated sometimes.  Viewing issues can be accompanied by a button to sign-up (sign-in beneath).

Attempting to edit the page accomplishes nothing.  The keystrokes are simply not accepted.

This was detected as part of verifying the cases as part of issue #797 analysis.

**Comment by carlyrevier** [comment]
@orcmid - Great catch! I've updated the instructions with all-new images.
