### ISSUE TITLE
Better Place Needed for sending newbies to GitHub

### ISSUE THREAD

**Issue by orcmid** [MicrosoftDocs/Contribute#802]
I assume that anyone attempting to use the Quick-Edit provision of the Contribute page and does not have a GitHub account and will consider signing up is likely some level of novice, even power-user, that is interested in contributing to Microsoft Learn documentation.

I do not recommend sending such interested parties to [github.com](https://github.com).  That may be overwhelming.  They are unlikely targets for the audience that page is created for.

An alternative is to suggest, that if a visitor to Contribute is interested in having a a free-to-use GitHub account, they be directed to [GitHub join](https;;/ghithub/join) directly for a personal signup.  It is still high-ceremony and possibly rebuffing; but it gets right to the point.

This is the location that GitHub uses from a button below issues that visitors without accounts, or signed-out, visit.

This also came up as part of investigations related to issue #797

**Comment by carlyrevier** [comment]
@orcmid - Excellent suggestion. I've updated the instructions to point to this location.
