### ISSUE TITLE
A large amount of information on pages of Microsoft Purview in Japanese language are missing.

### ISSUE THREAD

**Issue by futnag0** [MicrosoftDocs/Contribute#809]
A large amount of information on pages of Microsoft Purview in Japanese language are missing.
There are only five pages on Microsoft Purview in Japanese language.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Learn documentation contributor guide overview - Contributor guide](https://learn.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by carlyrevier** [comment]
Hi @futnag0 - Thank you for submitting this important feedback about the Purview documentation. However, you have reached the Issues queue for the Microsoft Learn [contributor guide](https://docs.microsoft.com/contribute/?branch=main), not a product.

Please share this feedback in the [Microsoft Feedback Portal](https://feedbackportal.microsoft.com/feedback). You can also leave this feedback on any page within the Purview documentation by selecting the "Feedback" button at the top of any article:

![image](https://github.com/MicrosoftDocs/Contribute/assets/23123030/59671ea8-f834-4b18-b5fb-47b4c9c905a2)

Thank you for helping make our documentation better!
