### ISSUE TITLE
Extension code

### ISSUE THREAD

**Issue by DonGlover** [MicrosoftDocs/Contribute#854]
I see that the code for the extensions are in private repositories. Are there any plans to open source the code?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b26339c-9a3c-de93-7806-3eb105b16ae4
* Version Independent ID: ec4aa25b-c7e2-db46-3cf1-7563e8031bd6
* Content: [Learn Authoring Pack for Visual Studio Code - Contributor guide](https://learn.microsoft.com/en-us/contribute/content/how-to-write-docs-auth-pack)
* Content Source: [Contribute/content/how-to-write-docs-auth-pack.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/content/how-to-write-docs-auth-pack.md)
* Product: **non-product-specific**
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by carlyrevier** [comment]
@meganbradley - Can you help with this question?

**Comment by carlyrevier** [comment]
@DonGlover - Sorry for the delay on this reply, but, unfortunately, no, there are no plans to make the code open source. We had to make the code internal for compliance reasons.
