### ISSUE TITLE
 Microsoft.AspNetCore.Mvc.Routing.UrlHelper.IsLocalUrl(String) method signature changed

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [MicrosoftDocs/Contribute#871]
Hi,

This page is written for aspnetcore-2.1:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.routing.urlhelper.islocalurl?view=aspnetcore-2.1&viewFallbackFrom=aspnetcore-6.0
and correctly describes the method signature as
```
public virtual bool IsLocalUrl (string url);
```

Since .NET 6, there's a change in signature related to nullable type. So for .NET 6, 7 and 8, the correct signature should be updated to:
```
public virtual bool IsLocalUrl (string? url);
```

Note the `?` after `string` argument.

Thank you

**Comment by carlyrevier** [comment]
Hi @pavel-mikula-sonarsource - You have reached the Issues queue for the Microsoft Learn [Contributor Home](https://learn.microsoft.com/contribute), not a product.

Issues submitted here are reviewed by the repo managers of Contributor Home, not product teams. Your issue should pertain to contributor content only. Requests for updates to products or product documentation will be closed.

If you have feedback about a product or product documentation, use one of these outlets instead:

- For Learn documentation: The feedback area at the top or bottom of an article. If there is none, post to our [Feedback Portal](https://feedbackportal.microsoft.com/feedback/).

- For Learn training content: The feedback link at the bottom of each unit. If there is none, use the Report feedback tool at the very bottom of [this article](https://learn.microsoft.com/training/support/troubleshooting?branch=main#report-feedback).

**Comment by pavel-mikula-sonarsource** [comment]
I'm indeed probably in the wrong repo. I was looking for repo with documentation, not the product itself.
