### ISSUE TITLE
#sign-off not needed in favor of the prmerger-automater

### ISSUE THREAD

**Issue by aroffe99** [MicrosoftDocs/Contribute#875]
Step 9 in https://learn.microsoft.com/en-us/contribute/content/how-to-write-quick-edits isn't necessarily needed.

The prmerger-automator bot seems to take care of notifying the author of the article in question. Any need a contributor would need to add sign-off?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4113452-bc7c-1f74-171a-7974db6e577a
* Version Independent ID: a4113452-bc7c-1f74-171a-7974db6e577a
* Content: [Edit Microsoft Learn documentation in the browser - Contributor guide](https://learn.microsoft.com/en-us/contribute/content/how-to-write-quick-edits)
* Content Source: [Contribute/content/how-to-write-quick-edits.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/content/how-to-write-quick-edits.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by carlyrevier** [comment]
Closing this issue.
