### ISSUE TITLE
Build Error CS1566 while trying to embed tar file in *.csproj

### ISSUE THREAD

**Issue by NishantThakkar** [MicrosoftDocs/Contribute#884]
**I am getting build error while trying to embed tar file:**

**File Size:** 2.46 GB

**Error:**
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1566	Error reading resource 'resource.tar.gz' -- 'Specified argument was out of the range of valid values.

**Embed code:**
![image](https://github.com/MicrosoftDocs/Contribute/assets/5793534/b742cb8b-f5f2-4674-9e19-ce75e16db46c)

**Comment by carlyrevier** [comment]
Hi @NishantThakkar - You have reached the Issues queue for the Microsoft Learn [Contributor Home](https://learn.microsoft.com/contribute), not a product.

Issues submitted here are reviewed by the repo managers of Contributor Home, not product teams. Your issue should pertain to contributor content only. Requests for updates to products or product documentation will be closed.

If you have feedback about a product or product documentation, use one of these outlets instead:

For Learn documentation: The feedback area at the top or bottom of an article. If there is none, post to our [Feedback Portal](https://feedbackportal.microsoft.com/feedback/).

For Learn training content: The feedback link at the bottom of each unit. If there is none, use the Report feedback tool at the very bottom of [this article](https://learn.microsoft.com/training/support/troubleshooting?branch=main#report-feedback).
