### ISSUE TITLE
Looking for a procedure to replace images in Architecture center

### ISSUE THREAD

**Issue by arntdg** [MicrosoftDocs/Contribute#920]
Hi!
I'm looking for a way to replace existing images in Architecture Center (and also Azure NetApp Files related) articles. Ed Price used to help me with this, and he used to replace an image for me, and also make the originating Visio or Powerpoint diagrams available through the download button underneath the image.
Kindly advise how this can be done, or who can assist me with this.
I currently have refreshed images ready for https://learn.microsoft.com/en-us/azure/architecture/example-scenario/file-storage/data-protection-kubernetes-astra-azure-netapp-files
Many thanks in advance.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6af2c4c0-687c-849f-9ce1-cfc3fbe3b374
* Version Independent ID: 6af2c4c0-687c-849f-9ce1-cfc3fbe3b374
* Content: [Overview of editing documentation on Microsoft Learn - Contributor guide](https://learn.microsoft.com/en-us/contribute/content/how-to-write-overview)
* Content Source: [Contribute/content/how-to-write-overview.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/content/how-to-write-overview.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by carlyrevier** [comment]
Hi @arntdg - Thanks for reaching out. Ed Price is no longer with Microsoft, but let me check with the Architecture Center team for who might be the right contact to help you with this.

**Comment by carlyrevier** [comment]
@arntdg - Closing this issue as I've replied internally.
