### ISSUE TITLE
Instructions to comment '#sign-off' on quick docs edits result in errors

### ISSUE THREAD

**Issue by zhanknight** [MicrosoftDocs/Contribute#940]
In the page [Edit Microsoft Learn documentation in the browser](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/content/how-to-write-quick-edits.md), the final instructions are to comment `#sign-off` on your PR to alert the team that the PR is ready to be reviewed. 

This seems to result in an instant comment from the 'permerger-automator' bot on some MS repos that the comment is invalid and only the assigned owner can use it: "Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. "

See [this PR for Azure Docs](https://github.com/MicrosoftDocs/azure-docs/pull/119235) for an example.

Does this need to be updated or removed?

**Comment by carlyrevier** [comment]
@zhanknight - Interesting find! Thank you for opening an issue and providing a clear example. I've never seen this before. I'm wondering if it's only in the Azure Docs repo. Have you seen this message in other MicrosoftDocs repos?

**Comment by zhanknight** [comment]
That was my first PR for MS Docs, so I hadn't seen it before. Just out of curiosity, I pulled up the most recently updated MicrosoftDocs repo (MicrosoftDocs/sql-docs right now) and found [this PR](https://github.com/MicrosoftDocs/sql-docs/pull/9614) from last week that has the same thing going on, so the prmerger-automator bot seems to be complaining in a few places.

**Comment by carlyrevier** [comment]
@zhanknight - I did some research internally and learned that the behavior you are seeing is expected! Great find. I'll update the instructions in this guide. Thank you!

**Comment by zhanknight** [comment]
@carlyrevier Glad I could help somehow. Thanks for maintaining those guides, they're great!
