### ISSUE TITLE
Contribution page links to non-existent anchor

### ISSUE THREAD

**Issue by petterh** [MicrosoftDocs/Contribute#945]
[This page](https://learn.microsoft.com/en-us/contribute/content/dotnet/dotnet-contribute) contains the following link. Which does point to a page, but the anchor is not on that page:

> https://learn.microsoft.com/en-us/contribute/content/#quick-edits-to-documentation

The context:

> For small changes, see [Quick edits to documentation](https://learn.microsoft.com/en-us/contribute/content/#quick-edits-to-documentation).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d80fc813-0f5a-a286-fc1c-c792c96c15b9
* Version Independent ID: cd89f9f6-c81b-e64e-49fb-54cf639eef37
* Content: [Contribute to the .NET documentation repositories - Contributor guide](https://learn.microsoft.com/en-us/contribute/content/dotnet/dotnet-contribute)
* Content Source: [Contribute/content/dotnet/dotnet-contribute.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/content/dotnet/dotnet-contribute.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by carlyrevier** [comment]
@petterh - Thanks for catching this! I'll update the article.
