### ISSUE TITLE
Share for enrollment- to track

### ISSUE THREAD

**Issue by gabbegabbelito** [MicrosoftDocs/Contribute#957]
Hi
I was going to create a collection, similar to the ones one can enroll to during Ignite.
So that I can track the ones enrolling (for a mandatory training we aim to host for Copilot pilot users). But seems I can’t create a collection, and when shared one must to enroll to the training? Or do I do something wrong? 

I think my PDMs and TPMs a few years back stated “only Microsoft employees can create these collections”, but I hoped that had changed?
If not - why not? And how can I create what I aim to do for our pilot?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b0bc433-19b3-0787-68c5-da2bab4f2634
* Version Independent ID: 3b0bc433-19b3-0787-68c5-da2bab4f2634
* Content: [Create and manage Microsoft Learn Collections - Contributor guide](https://learn.microsoft.com/en-us/contribute/content/collections)
* Content Source: [Contribute/content/collections.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/content/collections.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by carlyrevier** [comment]
Hi @gabbegabbelito - I'm not sure if you're asking about Official Collections or Cloud Skills Challenges, but in either case, both can be created only by Microsoft employees. You can create a regular collection, but unfortunately that doesn't allow you to track enrollment or allow people to enroll. As of today, I don't think there are any tools on Microsoft Learn that would allow non-Microsoft employees to do what you're trying to do.
