### ISSUE TITLE
Why SharePoint hasn't pretty like GitHub markdown.

### ISSUE THREAD

**Issue by yutsunoki** [MicrosoftDocs/Contribute#960]
Why SharePoint markdown is different with GitHub.

**Comment by carlyrevier** [comment]
Hi @yutsunoki - SharePoint and GitHub use different Markdown engines to render Markdown content. SharePoint uses a Markdown engine that is based on the CommonMark specification, while Github uses its own version of Markdown called GitHub Flavored Markdown. GFM includes additional features like task lists, tables, and syntax highlighting for code blocks, which are not available in CommonMark. Hope this helps!

**Comment by yutsunoki** [comment]
Yap, it is helpful. Thanks.
