### ISSUE TITLE
Pros&cons for the standard experience to provide feedback

### ISSUE THREAD

**Issue by MartinM85** [MicrosoftDocs/Contribute#964]
During 2024, GitHub issues will be replaced with a new feedback system.

Might I have some questions how the new feedback will work?

1. How does the team receiving the feedback can ask user for more information? 
2. How do I know if the documentation will be fixed?
3. How do I know when the documentation will be fixed?
4. How do I know if someone else already reported the issue to avoid duplicities?
5. How do I know if the feedback was sent and processed?
6. How does the translation to English work? It supports global accessibility for non-English learners, but from my experience translations from Czech to English don't work
7. Is Markdown supported in the form for providing the feedback?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe6e7ce4-21d7-4105-0be1-cc97203cfe78
* Version Independent ID: fe6e7ce4-21d7-4105-0be1-cc97203cfe78
* Content: [Provide feedback for Microsoft Learn content - Contributor guide](https://learn.microsoft.com/en-us/contribute/content/provide-feedback)
* Content Source: [Contribute/content/provide-feedback.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/content/provide-feedback.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by SanderSade** [comment]
I am not related to the Learn/Docs team, but the blog post https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635 goes a bit more into details.

**Comment by carlyrevier** [comment]
Thank you for your questions, @MartinM85. As you saw in the article, the feedback submitted through the new mechanism is now anonymous, so you will not be contacted after submitting the feedback and your feedback will not be published for others to see. 

Same as we did with Git issues, the teams will work through feedback and prioritize and plan changes. Once these changes are introduced, you'll be able to see them in the change history for the article. You can read more on how to access the change history in the topic you submitted this issue on. 

As far as knowing that the feedback was submitted, you will receive a confirmation message upon choosing **Submit** on the feedback window. On our end, we're processing all feedback irrespective of the language it's received in and routing it to the right teams. While we aren't able to act on all feedback we receive, we value all our customers’ input, and we take steps to review and prioritize it. 

Finally, and as you probably saw on this topic, we'll soon be deactivating GitHub Issues on this repository too, and while the current feedback mechanism doesn't support Markdown, we intend to continue to iterate the features and capabilities enabled.  Also, please note that the platform still allows you to submit public pull requests for content that had this capability enabled.

**Comment by Ballzer0** [comment]
This is heartbreaking 💔
