### ISSUE TITLE
Phasing out github issues

### ISSUE THREAD

**Issue by Ballzer0** [MicrosoftDocs/Contribute#965]
Phasing out github issues is a big mistake. Ive never gotten help from microsoft by using the "feedback" button. For example, if there is an acutal bug, and the software does not behave like the documentation says. Github issues was a great way to come into contact with the actaul team responsible for the issue.

I wont have a case id or other users to discuss my issue with if you make it all private

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe6e7ce4-21d7-4105-0be1-cc97203cfe78
* Version Independent ID: fe6e7ce4-21d7-4105-0be1-cc97203cfe78
* Content: [Provide feedback for Microsoft Learn content - Contributor guide](https://learn.microsoft.com/en-us/contribute/content/provide-feedback)
* Content Source: [Contribute/content/provide-feedback.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/content/provide-feedback.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by carlyrevier** [comment]
Hi @Ballzer0 - Thank you for your thoughts. We realize this change may take an adjustment for frequent GitHub users, and we hope to continue to receive your feedback through the new feedback system. 

While we continue to iterate and improve the features and capabilities enabled on the new feedback system, please keep in mind you will still be able to submit public pull requests for content that had this capability enabled. You can find more information here: [https://learn.microsoft.com/en-us/contribute/content/how-to-write-quick-edits ](https://learn.microsoft.com/en-us/contribute/content/how-to-write-quick-edits )
