### ISSUE TITLE
Please Monitor or Take a Poll on the New Feedback Mechanism After Implementing

### ISSUE THREAD

**Issue by jarredm-demo** [MicrosoftDocs/Contribute#966]
While the previous feedback method may not have been optimal, most people perceive a thumbs up/down feedback box as a dismissive way for a company/service to easily disregard feedback without follow-up.  It would be helpful if the documentation team took baseline polling (or asked a 3rd party company to conduct it on their behalf) before and after to measure if people felt more heard.

The perception that you cannot help/are not truly heard when documentation is broken greatly factors into satisfaction/dissatisfaction for a product.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe6e7ce4-21d7-4105-0be1-cc97203cfe78
* Version Independent ID: fe6e7ce4-21d7-4105-0be1-cc97203cfe78
* Content: [Provide feedback for Microsoft Learn content - Contributor guide](https://learn.microsoft.com/en-us/contribute/content/provide-feedback)
* Content Source: [Contribute/content/provide-feedback.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/content/provide-feedback.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by carlyrevier** [comment]
Thank you, @jarredm-demo, for your feedback. We have shared these updates with our MVP community and have received a lot of great feedback to help shape future capabilities and features. While we continue to iterate on them, we hope you’ll continue to share your feedback using the new feedback system or by submitting public pull requests for content that has this capability already enabled. You can find more information here: [https://learn.microsoft.com/en-us/contribute/content/how-to-write-quick-edits ](https://learn.microsoft.com/en-us/contribute/content/how-to-write-quick-edits )
